Repository Azure/azure-container-networking, pull requests merged in 2022-11, with the labels that each got.

#1686 Decrease pipeline AKS cluster cost
  hack/swift/Makefile
Labels: enhancement, ci

#1685 tool: [WIN-NPM] minor updates to windows script, and new linux script
  debug/windows/npm/README.md
  debug/windows/npm/pod_exec.ps1
  debug/windows/npm/win-debug.ps1
  debug/windows/npm/win-debug.sh
Labels: npm, windows

#1569 fix: [WIN-NPM] don't apply policy to new pod with same IP as an old pod
  npm/pkg/dataplane/dataplane-test-cases_windows_test.go
  npm/pkg/dataplane/dataplane_windows.go
  npm/pkg/dataplane/ipsets/ipset.go
  npm/pkg/dataplane/ipsets/ipset_windows.go
  npm/pkg/dataplane/ipsets/ipsetmanager_windows.go
  npm/pkg/dataplane/ipsets/ipsetmanager_windows_test.go
  npm/pkg/dataplane/testutils/utils_windows.go
Labels: npm

#1698 skip podtocidr(1.1.1.1:80) tests in cilium connectivity tests
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: ci

#1609 Add Cilium on AKS Overlay e2e scenario
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/overlay/overlay-e2e-job-template.yaml
  .pipelines/singletenancy/overlay/overlay-e2e-step-template.yaml
  .pipelines/submodules-pipeline.yaml
  dropgz/build/cniTest.Dockerfile
  hack/swift/Makefile
  test/integration/manifests/cns/overlayconfigmap.yaml
  test/integration/manifests/ip-masq-agent/config-custom.yaml
  test/integration/manifests/ip-masq-agent/config-reconcile.yaml
  test/integration/manifests/ip-masq-agent/ip-masq-agent.yaml
  test/integration/setup_test.go
Labels: ci

#1661 cancel pipeline on tag change
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/submodules-pipeline.yaml
Labels: work-in-progress, ci

#1669 fix: hide echo banner in log
  cns/healthserver/server.go
Labels: cns, fix

#1666 Migrate powershell docker scripts to docker@2
  .pipelines/containers/container-template-windows.yaml
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/pipeline.yaml
  .pipelines/submodules-pipeline.yaml
Labels: ci

#1566 fix: [NPM-LINUX] resiliency for several non-retriable errors
  npm/metrics/ai-utils.go
  npm/metrics/timer.go
  npm/pkg/dataplane/ipsets/ipset.go
  npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
  npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
  npm/pkg/dataplane/policies/chain-management_linux.go
  npm/pkg/dataplane/policies/policy_linux.go
  npm/util/ioutil/current-azure-chains.go
  npm/util/ioutil/restore.go
  npm/util/ioutil/restore_test.go
Labels: npm, linux
