Repository Azure/azure-container-networking, pull requests merged in 2023-09, with the labels that each got.

#2174 test(cyclonus): [WIN-NPM] fix consistent failure from not sleeping long enough
  .pipelines/npm/npm-conformance-tests.yaml
  test/cyclonus/test-cyclonus-windows.sh
Labels: npm, ci, windows

#2203 ci: Increase vmSize for dualstack overlay
  .pipelines/pipeline.yaml
Labels: ci

#2153 ci: Changing Service Connection for PR pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/load-test-templates/pod-deployment-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/load-test-templates/validate-state-template.yaml
  .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  .pipelines/templates/create-cluster.yaml
  .pipelines/templates/delete-cluster.yaml
Labels: ci

#2192 CNS - Ensuring no stale NCs during NNC reconcile
  cns/kubecontroller/nodenetworkconfig/reconciler.go
  cns/kubecontroller/nodenetworkconfig/reconciler_test.go
  cns/restserver/internalapi.go
  cns/restserver/internalapi_test.go
Labels: cns, fix

#2184 restruct zap logger for CNI
  cni/api/api.go
  cni/client/client.go
  cni/ipam/ipam.go
  cni/ipam/plugin/main.go
  cni/ipam/pluginv6/main.go
  cni/log/logger.go
  cni/log/logger_mock.go
  cni/network/invoker_azure.go
  cni/network/invoker_cns.go
  cni/network/multitenancy.go
  cni/network/network.go
  cni/network/network_linux.go
  cni/network/network_windows.go
  cni/network/plugin/main.go
  cni/plugin.go
  cni/telemetry/service/telemetrymain.go
  zaplog/zaplog.go
Labels: cni

#2193 Feat: Created a Network Container Status Section to be updated with the latest error code
  crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
  crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
Labels: cns, release/1.4, release/latest, needs-backport

#2206 ci: Increase timeout of datapath tests
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
Labels: ci

#2208 fix: serviceAccount must be specified at pod spec level in dual stack goldpinger deployments
  test/integration/manifests/datapath/linux-deployment-ipv6.yaml
  test/integration/manifests/datapath/linux-deployment.yaml
Labels: fix

#2218 Publishing our Windows dropgz version in linux dropgz manifest
  .pipelines/pipeline.yaml
  Makefile
Labels: dropgz

#2183 feat: CNS/CNI async pod delete
  cni/network/invoker_cns.go
  cns/client/client.go
  cns/configuration/configuration.go
  cns/configuration/configuration_test.go
  cns/fsnotify/fsnotify.go
  cns/fsnotify/fsnotify_test.go
  cns/service/main.go
  test/integration/manifests/cnsconfig/swiftconfigmap.yaml
Labels: enhancement, cns, cni, release/1.4, release/latest, needs-backport

#2141 ci: Add CNIv2 Linux to Load Test pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/load-test-templates/pod-deployment-template.yaml
  .pipelines/cni/load-test-templates/restart-cns-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/load-test-templates/validate-state-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
  test/integration/manifests/noop-deployment-linux.yaml
  test/integration/manifests/noop-deployment-windows.yaml
  test/validate/linux_validate.go
Labels: ci

#2226 [CNI] restruct CNI logger
  cni/api/api.go
  cni/client/client.go
  cni/ipam/ipam.go
  cni/log/logger.go
  cni/log/logger_linux.go
  cni/log/logger_mock.go
  cni/log/logger_windows.go
  cni/network/invoker_azure.go
  cni/network/plugin/main.go
  cni/plugin.go
  cni/telemetry/service/telemetrymain.go
  network/endpoint.go
  network/hnswrapper/hnsv1wrapper.go
  network/log/logger.go
  network/networkutils/networkutils_linux.go
  network/ovsinfravnet/infravnet_linux.go
  network/policy/policy_windows.go
  network/snat/snat_linux.go
  ovsctl/ovsctl.go
  zaplog/zaplog.go
Labels: cni

#2227 chore: making installation of CNS daemonset shared
  test/integration/datapath/datapath_linux_test.go
  test/integration/datapath/datapath_windows_test.go
  test/integration/k8s_test.go
  test/integration/load/load_test.go
  test/integration/setup_test.go
  test/internal/datapath/datapath_win.go
  test/internal/k8sutils/utils_create.go
  test/internal/kubernetes/label.go
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_create.go
  test/internal/kubernetes/utils_delete.go
  test/internal/kubernetes/utils_get.go
  test/internal/kubernetes/utils_parse.go
  test/validate/utils.go
  test/validate/validate.go
Labels: ci

#2201 feat: CNS/CNI async delete changes for azure-ipam
  azure-ipam/go.mod
  azure-ipam/go.sum
  azure-ipam/ipam.go
  test/integration/manifests/cnsconfig/ciliumconfigmap.yaml
Labels: enhancement, swift, azure-ipam, release/1.4, release/latest, needs-backport

#2213 chore: consolidate core dependencies upgrade
  .github/workflows/codeql.yaml
  .github/workflows/crdgen.yaml
  .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
  .github/workflows/cyclonus-netpol-test.yaml
  .github/workflows/golangci.yaml
  go.mod
  go.sum
Labels: dependencies

#2188 migrate to patch for NNC spec updates
  cns/ipampool/monitor.go
  cns/ipampool/monitor_test.go
  cns/kubecontroller/nodenetworkconfig/scopedclient.go
Labels: cns, swift

#2232 CNI async delete after ReleaseIPAddress
  cni/network/invoker_cns.go
Labels: cni, swift, release/1.4, release/latest, needs-backport

#2241 ci: Add CNIv1 Linux to Load Test Pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  hack/aks/Makefile
  test/validate/linux_validate.go
Labels: cni, ci

#2224 Adding overlay v4/dualstack conflists to Windows Dropgz
  dropgz/build/windows.Dockerfile
Labels: dropgz

#2013 proposal: redesign of CNS IPAM
  docs/feature/ipammath/0-background.md
  docs/feature/ipammath/1-ipam-math.md
  docs/feature/ipammath/1-watchpods.md
Labels: enhancement, cns, swift, docs

#2247 test: [NPM] skip cyclonus for test dir
  .github/workflows/cyclonus-netpol-test.yaml
Labels: npm, ci, linux

#2255 fix: skipping the k8s e2e unsupported service conformance test
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: fix, ci

#2244 Create initial contrbuting guides
  CONTRIBUTING.md
  docs/contributing/git.md
  docs/contributing/github.md
  docs/contributing/go.md
Labels: docs

#2251 ci: removing the submodules pipeline as PR pipeline covers the checks
  .pipelines/submodules-pipeline.yaml
Labels: cni, ci

#2256 backport "fix: skipping the k8s e2e unsupported service conformance test (#2255)" to release/v1.4
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: fix, ci, release/1.4

#2253 fix: set cluster auto-upgrade and node auto-upgrade in the hackfile
  hack/aks/Makefile
Labels: fix, ci

#2258 fix: cluster template env vars
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/templates/create-cluster.yaml
  Makefile
Labels: fix

#2242 submodule dependency updates
  azure-ipam/go.mod
  azure-ipam/go.sum
  dropgz/go.mod
  dropgz/go.sum
  go.mod
  zapai/go.mod
  zapai/go.sum
Labels: dependencies

#2187 v4overlay windows test cases
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  hack/aks/Makefile
  hack/aks/README.md
  test/integration/datapath/datapath_windows_test.go
  test/integration/load/load_test.go
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_create.go
  test/validate/linux_validate.go
  test/validate/utils.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: ci

#2230 ci: add CNIv2 testing for different proc/OS
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  hack/aks/Makefile
Labels: cni, ci

#2261 ci: Add HNS restart to Windows CNIv1 in Load Test Pipeline
  .pipelines/cni/load-test-templates/restart-hns-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  test/integration/manifests/load/privileged-daemonset-windows.yaml
Labels: cni, ci
