Repository Azure/azure-container-networking, pull requests merged in 2023-12, with the labels that each got.

#2419 fix: disable ipv6 on transparent vlan mode network create
  network/network_linux.go
Labels: cni, fix, multitenancy

#2424 ci: fix for cilium connectivity merged upstream
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Labels: ci

#2427 fix: add contexts to clean up fsnotify goroutines
  cns/fsnotify/fsnotify.go
  cns/service/main.go
  go.mod
  go.sum
Labels: cns, fix, release/1.4, release/latest, needs-backport

#2431 feat: enable readyz/healthz endpoints
  cns/healthserver/server.go
  cns/service/main.go
Labels: enhancement, cns

#2440 go submodules dependency updates
  azure-ipam/go.mod
  azure-ipam/go.sum
  build/tools/go.mod
  build/tools/go.sum
  dropgz/go.mod
  dropgz/go.sum
  zapai/go.sum
Labels: dependencies

#2441 ci: Add vnetscale cluster delete
  .pipelines/pipeline.yaml
Labels: ci

#2439 update stale workflow
  .github/workflows/stale.yaml
Labels: ci

#2448 fix: change to new-from-rev master in lint action
  .github/workflows/golangci.yaml
  .golangci.yml
  Makefile
Labels: ci

#2399 ci: Modify ACN PR pipeline for merge queue use
  .github/workflows/codeql.yaml
  .github/workflows/crdgen.yaml
  .github/workflows/golangci.yaml
  .pipelines/pipeline.yaml
Labels: enhancement

#2456 ci: revert codeQL checks to apart of merge queue runs
  .github/workflows/codeql.yaml
Labels: ci

#2457 revert: submodule path exclusion
  .pipelines/pipeline.yaml
Labels: ci
