Repository Azure/azure-container-networking, pull requests merged in 2023-08, with the labels that each got.

#2075 feat: [dropgz] Dropgz for windows
  .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  Makefile
  dropgz/build/cniTest_linux.Dockerfile
  dropgz/build/cniTest_windows.Dockerfile
  dropgz/build/windows.Dockerfile
  dropgz/pkg/embed/payload.go
  test/integration/manifests/cni/cni-installer-v1-windows.yaml
Labels: cni, feature

#2096 chore: add release branches to pr pipeline trigger (#2095)
  .pipelines/pipeline.yaml
Labels: ci

#2097 ci: Remove window cni binaries update code
  Makefile
  cni/build/windows.Dockerfile
  hack/scripts/updatecni.ps1
Labels: cni, ci

#2047 refactor: [CI-CNI] Removing the predefined interfaces from validate
  Makefile
  test/integration/load/load_test.go
  test/validate/linux_validate.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: cni, ci

#2079 CNS - consider multiple IPs for a pod in reconciliation after restart
  cns/client/client_test.go
  cns/cnireconciler/podinfoprovider.go
  cns/restserver/internalapi.go
  cns/restserver/internalapi_test.go
  cns/service/main.go
Labels: cns, swift

#2088 CI: add variable for node count
  .pipelines/cni/pipeline.yaml
Labels: ci

#2109 ci: Paramterize test-validate-state
  .pipelines/cni/load-test-templates/validate-state-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  Makefile
Labels: ci

#2093 Swift v2 CNS design
  docs/feature/dualstack/cilium-dualstack.md
  docs/feature/swift-v2/cns.md
Labels: cns, docs

#2104 ci: Update dns tests for k8s conformance
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
Labels: ci

#2108 ci: adding cni package as a trigger
  .pipelines/submodules-pipeline.yaml
Labels: ci

#2107 put back the config to write logs to the file instead of only stdout logs
  cni/ipam/plugin/main.go
  cni/ipam/pluginv6/main.go
  cni/network/plugin/main.go
Labels: cni

#2106 ci: Enable /azp run for submodule pipeline
  .pipelines/submodules-pipeline.yaml
Labels: ci

#2105 ci: [CNI] [NPM] Add NPM|CNI integration test to load-test pipeline.
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
Labels: npm, cni, ci

#2098 ci: dualstack overlay linux test cases
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  hack/aks/Makefile
  hack/aks/README.md
  test/integration/datapath/datapath_linux_test.go
  test/integration/load/load_test.go
  test/integration/setup_test.go
  test/validate/linux_validate.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: ci

#2076 fix: updating CNI to v1.5.9 for dropgz
  dropgz/build/linux.Dockerfile
  dropgz/build/windows.Dockerfile
Labels: cni

#1716 fix: deadlock when os.Stat errors within rotate method
  log/logger.go
  log/logger_test.go
Labels: fix, telemetry

#2111 [Multitenancy] : Add MT PodNetworkConfig CRD
  .github/workflows/crdgen.yaml
  crd/multitenantpodnetworkconfig/Makefile
  crd/multitenantpodnetworkconfig/README.md
  crd/multitenantpodnetworkconfig/api/v1alpha1/groupversion_info.go
  crd/multitenantpodnetworkconfig/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenantpodnetworkconfig/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenantpodnetworkconfig/client.go
  crd/multitenantpodnetworkconfig/embed.go
  crd/multitenantpodnetworkconfig/embed_test.go
  crd/multitenantpodnetworkconfig/manifests/acn.azure.com_multitenantpodnetworkconfigs.yaml
  crd/multitenantpodnetworkconfig/manifests/doc.go
Labels: cns, multitenancy, swift-v2

#2113 [Multitenancy]: Add NodeInfo crd
  .github/workflows/crdgen.yaml
  crd/nodeinfo/Makefile
  crd/nodeinfo/README.md
  crd/nodeinfo/api/v1alpha1/groupversion_info.go
  crd/nodeinfo/api/v1alpha1/nodeinfo.go
  crd/nodeinfo/api/v1alpha1/zz_generated.deepcopy.go
  crd/nodeinfo/client.go
  crd/nodeinfo/embed.go
  crd/nodeinfo/embed_test.go
  crd/nodeinfo/manifests/acn.azure.com_nodeinfo.yaml
  crd/nodeinfo/manifests/doc.go
Labels: cns, multitenancy, swift-v2

#2132 chore: Adding CNI codeowners
  .github/CODEOWNERS
Labels: cni

#2100 chore: log process id instead of logging name
  cni/log/logger.go
Labels: cni

#2077 ci:[CNI] ACN PR Pipeline speed improvements
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/cni/k8s-e2e/k8s-e2e-step-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  .pipelines/submodules-pipeline.yaml
  .pipelines/templates/create-cluster.yaml
  .pipelines/templates/delete-cluster.yaml
  hack/aks/Makefile
  hack/aks/README.md
  test/internal/k8sutils/utils.go
Labels: cni, ci

#2090 fix: overlay IPAM not reporting version
  Makefile
  azure-ipam/main.go
Labels: fix, azure-ipam

#2085 ci: cilium scale pipeline
  .pipelines/cni/cilium/cilium-scale-test.yaml
  hack/aks/Makefile
  hack/manifests/apache.yaml
  hack/manifests/netperf-pod.yaml
  hack/scripts/netperf.sh
  test/scale/label-nodes.sh
Labels: ci

#2133 [Multitenancy]: Add PodNetwork CRD
  .github/workflows/crdgen.yaml
  crd/external/podnetwork/Makefile
  crd/external/podnetwork/README.md
  crd/external/podnetwork/api/v1alpha1/groupversion_info.go
  crd/external/podnetwork/api/v1alpha1/podnetwork.go
  crd/external/podnetwork/api/v1alpha1/zz_generated.deepcopy.go
  crd/external/podnetwork/client.go
  crd/external/podnetwork/embed.go
  crd/external/podnetwork/embed_test.go
  crd/external/podnetwork/manifests/acn.azure.com_podnetworks.yaml
  crd/external/podnetwork/manifests/doc.go
Labels: cns, multitenancy, swift-v2

#2143 zap: change cni component structure
  cni/ipam/ipam.go
  cni/ipam/plugin/main.go
  cni/ipam/pluginv6/main.go
  cni/log/logger.go
  cni/network/invoker_azure.go
  cni/network/invoker_cns.go
  cni/network/multitenancy.go
  cni/network/network.go
  cni/network/network_windows.go
  cni/network/plugin/main.go
  cni/plugin.go
  cni/telemetry/service/telemetrymain.go
Labels: cni

#2147 fix: correct make cmd for creating cilium cluster
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
Labels: ci

#2146 fix: Add back cluster create/delete for Cilium Nightly Pipeline
  .pipelines/cni/cilium/nightly-release-test.yml
Labels: fix

#2101 perf: 🚀 Increase CNI Lock Timeout to 30 seconds for Linux AKS.
  cni/plugin.go
  store/json.go
Labels: cni

#2154 ci: add packages for submodule trigger
  .pipelines/submodules-pipeline.yaml
Labels: ci

#2151 [Multitenancy]: Add PodNetwork field to MTPNC spec
  crd/multitenantpodnetworkconfig/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenantpodnetworkconfig/manifests/acn.azure.com_multitenantpodnetworkconfigs.yaml
Labels: cns, swift, swift-v2

#2150 fix: Remove NLM_F_EXCL flag from Netlink Delete call
  netlink/ip_linux.go
  netlink/netlink_test.go
Labels: cni, fix

#2157 fix: Remove NLM_F_EXCL flag from Netlink Delete call (#2150)
  netlink/ip_linux.go
  netlink/netlink_test.go
Labels: cni, fix

#2152 ci: add node and CNS restart test case for v4overlay cluster
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
Labels: ci

#2138 docs: proposal for async pod delete handling
  docs/feature/async-delete/cni.md
  docs/feature/async-delete/cns.md
  docs/feature/async-delete/readme.md
Labels: cns, docs

#2112 feat: stub CNS Pod watcher
  cns/configuration/configuration.go
  cns/kubecontroller/nodenetworkconfig/reconciler.go
  cns/kubecontroller/podwatcher/podwatcher.go
  cns/service/main.go
Labels: cns, swift, swift-v2

#2161 hotfix for adding duplicated routes
  network/transparent_endpointclient_linux.go
Labels: cni

#2158 fix: Remove NLM_F_EXCL flag from Netlink Delete call (#2150)
  netlink/ip_linux.go
  netlink/netlink_test.go
Labels: cni, fix

#2170 chore: update azure-cni version in dropgz
  dropgz/build/cni.Dockerfile
Labels: cni

#2162 Upgrade controller-runtime
  build/tools/go.mod
  build/tools/go.sum
  cns/multitenantcontroller/mockclients/kubeclient_generated.go
  cns/multitenantcontroller/multitenantoperator/multitenantcrdcontroller.go
  cns/service/main.go
  crd/clustersubnetstate/api/v1alpha1/zz_generated.deepcopy.go
  crd/clustersubnetstate/manifests/acn.azure.com_clustersubnetstates.yaml
  crd/external/podnetwork/api/v1alpha1/zz_generated.deepcopy.go
  crd/external/podnetwork/manifests/acn.azure.com_podnetworks.yaml
  crd/external/podnetworkinstance/api/v1alpha1/zz_generated.deepcopy.go
  crd/external/podnetworkinstance/manifests/acn.azure.com_podnetworkinstances.yaml
  crd/multitenantnetworkcontainer/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenantnetworkcontainer/manifests/networking.azure.com_multitenantnetworkcontainers.yaml
  crd/multitenantpodnetworkconfig/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenantpodnetworkconfig/manifests/acn.azure.com_multitenantpodnetworkconfigs.yaml
  crd/nodeinfo/api/v1alpha1/zz_generated.deepcopy.go
  crd/nodeinfo/manifests/acn.azure.com_nodeinfo.yaml
  crd/nodenetworkconfig/api/v1alpha/zz_generated.deepcopy.go
  crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
  go.mod
  go.sum
Labels: cns, dependencies, swift-v2

#2110 feat: CNS writes SWIFT conflist
  cns/cniconflist/generator.go
  cns/cniconflist/generator_linux.go
  cns/cniconflist/generator_linux_test.go
  cns/cniconflist/generator_windows.go
  cns/cniconflist/testdata/fixtures/azure-linux-swift.conflist
  cns/service/main.go
Labels: enhancement, cns

#2171 Ankaggar/consolidate crds
  .github/workflows/crdgen.yaml
  crd/external/podnetwork/Makefile
  crd/external/podnetwork/README.md
  crd/external/podnetwork/api/v1alpha1/zz_generated.deepcopy.go
  crd/external/podnetwork/client.go
  crd/external/podnetwork/embed.go
  crd/external/podnetwork/embed_test.go
  crd/external/podnetwork/manifests/doc.go
  crd/external/podnetworkinstance/Makefile
  crd/external/podnetworkinstance/README.md
  crd/external/podnetworkinstance/api/v1alpha1/groupversion_info.go
  crd/external/podnetworkinstance/api/v1alpha1/zz_generated.deepcopy.go
  crd/external/podnetworkinstance/client.go
  crd/external/podnetworkinstance/embed.go
  crd/external/podnetworkinstance/embed_test.go
  crd/external/podnetworkinstance/manifests/doc.go
  crd/multitenancy/Makefile
  crd/multitenancy/README.md
  crd/multitenancy/api/v1alpha1/groupversion_info.go
  crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenancy/api/v1alpha1/nodeinfo.go
  crd/multitenancy/api/v1alpha1/podnetwork.go
  crd/multitenancy/api/v1alpha1/podnetworkinstance.go
  crd/multitenancy/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenancy/client.go
  crd/multitenancy/embed.go
  crd/multitenancy/embed_test.go
  crd/multitenancy/manifests/doc.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
  crd/multitenantpodnetworkconfig/README.md
  crd/multitenantpodnetworkconfig/api/v1alpha1/groupversion_info.go
  crd/multitenantpodnetworkconfig/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenantpodnetworkconfig/client.go
  crd/multitenantpodnetworkconfig/embed.go
  crd/multitenantpodnetworkconfig/embed_test.go
  crd/nodeinfo/Makefile
  crd/nodeinfo/README.md
  crd/nodeinfo/api/v1alpha1/groupversion_info.go
  crd/nodeinfo/api/v1alpha1/zz_generated.deepcopy.go
  crd/nodeinfo/client.go
  crd/nodeinfo/embed.go
  crd/nodeinfo/embed_test.go
  crd/nodeinfo/manifests/doc.go
Labels: cns, swift-v2

#2163 Add NotFound error handling to NMAgent client
  nmagent/client.go
  nmagent/client_test.go
  nmagent/error.go
Labels: swift

#2135 ci: add node and CNS restart test case in dualstack
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  Makefile
Labels: ci

#2176 update swiftv2 crds scope
  crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenancy/api/v1alpha1/nodeinfo.go
  crd/multitenancy/api/v1alpha1/podnetwork.go
  crd/multitenancy/api/v1alpha1/podnetworkinstance.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
Labels: cns, swift-v2

#2185 ci: Bypass Dualstack E2E on cluster creation failure
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/templates/create-cluster.yaml
Labels: ci

#2164 Add MTPNC reconciler for cache population in Swift V2
  cns/kubecontroller/multitenantpodnetworkconfig/reconciler.go
  cns/kubecontroller/pod/reconciler.go
  cns/service/main.go
  go.mod
  go.sum
Labels: cns, swift-v2

#2172 change total IPs and add secondary IP metric
  cns/ipampool/metrics.go
  cns/ipampool/monitor.go
Labels: cns, swift, fix

#2186 Update MTPNC scope
  crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
Labels: cns, swift-v2

#2115 fix: don't delete an existing conflist
  internal/fs/atomic.go
  internal/fs/atomic_test.go
Labels: cns

#2189 fix: don't delete an existing conflist (#2115)
  fs/atomic.go
  fs/atomic_test.go
Labels: cns, fix

#2194 fix: add OS=windows to manifest-add args
  Makefile
Labels: fix, ci
