Repository Azure/azure-container-networking, pull requests merged in 2023-10, with the labels that each got.

#2102 feat: 🌈 StatelessCNI: Adding getEndpoint and UpdateEndpoint API to CNS
  cns/NetworkContainerContract.go
  cns/api.go
  cns/client/client.go
  cns/client/client_test.go
  cns/restserver/ipam.go
  cns/restserver/restserver.go
  cns/service/main.go
Labels: cns, cni

#2262 ci: dualstack overlay windows test cases
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/cni/k8s-e2e/k8s-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  test/integration/manifests/cnsconfig/azurecnidualstackoverlaywindowsconfigmap.yaml
  test/internal/datapath/datapath_win.go
  test/internal/kubernetes/utils_create.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: ci

#2264 ci: Add log template to PR and Load Test Pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/cni/load-test-templates/pod-deployment-template.yaml
  .pipelines/cni/load-test-templates/restart-cns-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/templates/log-template.yaml
  test/integration/manifests/load/privileged-daemonset.yaml
Labels: ci

#2266 [CNI] zap logger telemetry package
  cni/network/plugin/main.go
  cni/plugin.go
  cni/telemetry/service/telemetrymain.go
  cnms/service/networkmonitor.go
  cns/service/main.go
  telemetry/aiwrapper.go
  telemetry/aiwrapper_test.go
  telemetry/telemetry.go
  telemetry/telemetry_test.go
  telemetry/telemetrybuffer.go
  telemetry/telemetrybuffer_test.go
Labels: cni

#2272 ci: Agent pool default set at stage level
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
Labels: ci

#2274 ci: v4overlay conformance test cases
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
Labels: ci

#2267 test(capz): [WIN-NPM] support containerd 1.7 filesystem
  npm/azure-npm.yaml
  npm/examples/windows/azure-npm-capz.yaml
  npm/examples/windows/azure-npm.yaml
Labels: npm, ci, windows

#2275 feat: create stateless cni binary for swift
  Makefile
Labels: cni

#2278 fix: change artifact naming convention
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/cni/load-test-templates/pod-deployment-template.yaml
  .pipelines/cni/load-test-templates/restart-cns-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/templates/log-template.yaml
Labels: fix, ci

#2280 ci: Parameterize CNS image repository
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_create.go
Labels: ci

#2282 Fix: Update pni scope to namespaced
  crd/multitenancy/api/v1alpha1/podnetworkinstance.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
Labels: cns, swift-v2

#2277 ci: Add control through environment variables for CNI Load Test
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
Labels: ci

#2233 [CNI] zap logger for platform package
  aitelemetry/telemetrywrapper_test.go
  cni/network/network.go
  cni/network/plugin/main.go
  cni/telemetry/service/telemetrymain.go
  cnm/network/network.go
  cnms/service/networkmonitor.go
  cns/dockerclient/dockerclient.go
  cns/restserver/util.go
  ebtables/ebtables.go
  ipam/manager.go
  ipam/manager_test.go
  iptables/iptables.go
  network/endpoint_windows.go
  network/endpoint_windows_test.go
  network/manager.go
  network/network_linux.go
  ovsctl/ovsctl.go
  platform/mockexec.go
  platform/os.go
  platform/osInterface.go
  platform/os_linux.go
  platform/os_test.go
  platform/os_windows.go
  platform/os_windows_test.go
  platform/windows/adapter/mellanox/mellanox.go
  telemetry/telemetry.go
  telemetry/telemetry_windows.go
  telemetry/telemetrybuffer.go
  telemetry/telemetrybuffer_test.go
Labels: cni

#2289 ci: Add NPM arm64 to CNI Load Test Pipeline
  .pipelines/cni/pipeline.yaml
Labels: ci

#2291 revert: Cilium load test RBAC
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Labels: ci

#2292 ci: Enable multiple runs with the same commitID
  .pipelines/cni/pipeline.yaml
  .pipelines/pipeline.yaml
Labels: ci

#2239 Adding dualstack overlay support to azure-ipam plugin for Cilium
  azure-ipam/const.go
  azure-ipam/ipam.go
  azure-ipam/ipam_test.go
  azure-ipam/ipconfig/ipconfig.go
Labels: azure-ipam

#2302 Adding CNI async delete to old API for cilium
  azure-ipam/ipam.go
Labels: azure-ipam

#2310 ci: move hubble connectivity tests to nightly pipeline
  .gitignore
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  hack/toolbox/server/Dockerfile.heavy
  test/integration/manifests/cilium/cilium-config-hubble.yaml
  test/integration/manifests/cilium/hubble/hubble-peer-svc.yaml
  test/integration/networkobservability/hubble_test.go
Labels: cni, ci

#2309 fix: retry pool allocation after cleaning IPAM state
  cni/network/invoker_azure.go
Labels: cni, fix

#2327 fix: Pipeline agent image update from 18.04 to 22.04 | AzSecPack
  .pipelines/containers/manifest-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  Makefile
  network/network_linux.go
Labels: fix, needs-backport

#2314 fix: Using retryOnConflict to fix v4overlay scale tests failing.
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  test/internal/kubernetes/utils.go
Labels: fix, ci

#2303 fix: improper field change
  .pipelines/pipeline.yaml
Labels: fix, ci

#2290 [cni]: dualstack overlay hostIP issue hotfix
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  cni/network/network.go
  cni/network/network_linux.go
  cni/network/network_windows.go
  cni/network/network_windows_test.go
Labels: cni

#2215 add a new container type for l1vh singularity container request
  cns/NetworkContainerContract.go
  cns/restserver/util.go
Labels: cns

#2299 [CNI] Migrate zap logger for acn ipam package
  cni/ipam/ipam.go
  cni/network/network.go
  ipam/azure.go
  ipam/fileIpam.go
  ipam/ipv6Ipam.go
  ipam/manager.go
  ipam/pool.go
  network/transparent_vlan_endpointclient_linux.go
  ovsctl/ovsctl.go
Labels: cni

#2334 ci: remove unused cilium files
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/cilium/cilium-scale-test.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  cilium/cilium_helm_values.yaml
  cilium/configmap.yaml
Labels: ci

#2332 update dropgz with azure-ipam/v0.0.5
  dropgz/build/linux.Dockerfile
Labels: dropgz

#2217 build: [NPM] update repo for ubuntu 20
  npm/linux.Dockerfile
Labels: npm, linux

#2324 feat: build cni installer image with cni builds
  .pipelines/pipeline.yaml
  Makefile
  cni/linux.Dockerfile
  cni/windows.Dockerfile
Labels: enhancement, cni, release/1.4, release/latest, needs-backport, dropgz

#2300 feat: CNS RequestIPAddress branching for MT/V2
  cni/plugin.go
  cns/NetworkContainerContract.go
  cns/api.go
  cns/azure-cns.yaml
  cns/configuration/env.go
  cns/configuration/env_test.go
  cns/fakes/cnsfake.go
  cns/middlewares/mock/mockClient.go
  cns/middlewares/mock/mockSWIFTv2.go
  cns/middlewares/swiftV2.go
  cns/middlewares/swiftV2_test.go
  cns/middlewares/utils/utils.go
  cns/middlewares/utils/utils_test.go
  cns/restserver/internalapi_test.go
  cns/restserver/ipam.go
  cns/restserver/ipam_test.go
  cns/restserver/restserver.go
  cns/restserver/util.go
  cns/service/main.go
  go.mod
  go.sum
Labels: cns, swift-v2

#2321 fix: Add SubnetGUID to MT PodNetwork CRD
  crd/multitenancy/api/v1alpha1/podnetwork.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
Labels: swift-v2
