Repository Azure/azure-container-networking, pull requests merged in 2023-11, with the labels that each got.

#2296 ci: add Cilium OS/Proc coverage to CNI Load Test pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
Labels: ci

#2337 Stateless CNI migration code.
  cns/restserver/ipam.go
Labels: do-not-merge, cni

#2330 feat: cni refactor for swift v2
  cni/network/invoker.go
  cni/network/invoker_azure.go
  cni/network/invoker_azure_test.go
  cni/network/invoker_cns.go
  cni/network/invoker_cns_test.go
  cni/network/invoker_mock.go
  cni/network/multitenancy.go
  cni/network/multitenancy_mock.go
  cni/network/multitenancy_test.go
  cni/network/network.go
  cni/network/network_test.go
  cni/network/network_windows.go
  cni/network/network_windows_test.go
  cnm/network/network.go
  cnms/service/networkmonitor.go
  netio/mocknetio.go
  netio/netio.go
  network/endpoint.go
  network/endpoint_linux.go
  network/endpoint_test.go
  network/endpoint_windows.go
  network/manager.go
  network/manager_mock.go
  network/mock_endpointclient.go
  network/mock_namespace.go
  network/namespace.go
  network/namespace_linux.go
  network/namespace_windows.go
  network/secondary_endpoint_client_linux.go
  network/secondary_endpoint_linux_test.go
  network/transparent_endpoint_linux_test.go
  network/transparent_endpointclient_linux.go
  network/transparent_vlan_endpointclient_linux.go
Labels: swift-v2

#2335 fix: enable ip forward on transparent vlan network create
  network/network_linux.go
  network/network_test.go
  network/networkutils/networkutils_linux.go
Labels: cni, fix

#2347 ci: Add k8s conformance to cilium E2E | Increase test timeouts cilium connectivity test
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: fix, ci

#2342 chores: SWIFT v2 routing changes
  cns/configuration/env.go
  cns/configuration/env_test.go
  cns/middlewares/mock/mockSWIFTv2.go
  cns/middlewares/swiftV2.go
  cns/middlewares/swiftV2_test.go
Labels: cns, swift-v2

#2343 normalize NCID by stripping Swift prefix
  cns/restserver/api_test.go
  cns/restserver/internalapi.go
  cns/restserver/util.go
Labels: cns, swift, fix, multitenancy, release/latest

#2353 backport: Pipeline agent image update from 18.04 to 22.04 | AzSecPack (#2327) to release/v1.4
  .pipelines/containers/manifest-template.yaml
  Makefile
  network/network_linux.go
Labels: fix, ci, release/1.4

#2351 backport updated client-go
  go.mod
  go.sum
Labels: cns, release/1.4

#2345 test: validate secondary endpoint client failure
  cni/network/invoker_cns.go
  cni/network/network.go
  netio/mocknetio.go
  netlink/mocknetlink.go
  network/endpoint.go
  network/endpoint_linux.go
  network/endpoint_test.go
  network/endpoint_windows.go
  network/manager.go
  network/secondary_endpoint_client_linux.go
  network/transparent_endpointclient_linux.go
Labels: swift-v2

#2336 test: add multitenancy transparent vlan conflist to dropgz
  cni/linux.Dockerfile
  dropgz/build/cniTest_linux.Dockerfile
Labels: dropgz

#2305 ci: Move E2E runtime variables from job level to stage
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
Labels: ci

#2358 ci: Update makefile cluster creation
  hack/aks/Makefile
Labels: ci

#2354 ci: Parameterize dropgz input for all Release pipeline scenarios
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
Labels: ci

#2356 ci: Update RDMA vmSku
  .pipelines/cni/pipeline.yaml
Labels: ci

#2362 fix: Cilium CLI version
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: fix

#2359 fix: validate that NCIDs are well-formed GUIDs
  cns/NetworkContainerContract.go
  cns/NetworkContainerContract_test.go
  cns/networkcontainers/networkcontainers.go
  cns/networkcontainers/networkcontainers_linux.go
  cns/networkcontainers/networkcontainers_windows.go
  cns/restserver/api.go
  cns/restserver/api_test.go
  cns/restserver/util.go
Labels: cns, fix, release/1.4, release/latest, needs-backport

#2364 fix: validate that NCIDs are well-formed GUIDs (#2359)
  cns/NetworkContainerContract.go
  cns/NetworkContainerContract_test.go
  cns/networkcontainers/networkcontainers.go
  cns/networkcontainers/networkcontainers_linux.go
  cns/networkcontainers/networkcontainers_windows.go
  cns/restserver/api.go
  cns/restserver/api_test.go
  cns/restserver/util.go
Labels: cns, fix, release/1.4

#2344 fix zap logger rotation issues
  cni/ipam/plugin/main.go
  cni/ipam/pluginv6/main.go
  cni/network/network.go
  cni/network/plugin/main.go
Labels: cni

#2357 fix: cni should not invoke cns to release ips for muiltitenancy
  cni/network/network.go
Labels: release/1.4, release/latest, needs-backport

#2365 fix: Match Cilium CLI to Cilium Agent
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: fix, ci

#2368 chore: Update hcsshim v0.11.4
  azure-ipam/go.mod
  azure-ipam/go.sum
  go.mod
  go.sum
Labels: ci

#2377 ci: Skip cilium encryption tests
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: ci

#2370 chore: Update goproxy v0.0.0-20231031074852-3ec07828be7a
  azure-ipam/go.mod
  azure-ipam/go.sum
  go.mod
  go.sum
Labels: ci

#2369 chore: Update handlers v1.5.2
  azure-ipam/go.mod
  azure-ipam/go.sum
  go.mod
  go.sum
Labels: ci

#2379 ci: validate async delete
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  hack/scripts/async-delete-test.sh
  test/integration/manifests/cnsconfig/overlayconfigmap.yaml
Labels: ci

#2361 refactor: remove cniTypesCurr.Result dependency in InterfaceInfo
  cni/network/invoker.go
  cni/network/invoker_azure.go
  cni/network/invoker_azure_test.go
  cni/network/invoker_cns.go
  cni/network/invoker_cns_test.go
  cni/network/invoker_mock.go
  cni/network/multitenancy.go
  cni/network/multitenancy_mock.go
  cni/network/multitenancy_test.go
  cni/network/network.go
  cni/network/network_linux.go
  cni/network/network_linux_test.go
  cni/network/network_windows.go
  cni/network/network_windows_test.go
  network/endpoint.go
  network/secondary_endpoint_client_linux.go
Labels: swift-v2

#2393 ci: bypass metric check for cilium nightly
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Labels: ci

#2389 ci: Update hcsshim in /azure-ipam
  azure-ipam/go.mod
  azure-ipam/go.sum
Labels: ci

#2398 fix: cilium config for hubble in cilium nightly pipeline
  test/integration/manifests/cilium/cilium-config-hubble.yaml
Labels: ci

#2407 ci: Improve Cilium nightly pipeline
  .pipelines/cni/cilium/nightly-release-test.yml
Labels: ci

#2372 chore: migrate to azure-cni and azure-ipam from dropgz-test
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/linux-cniv2-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  Makefile
  azure-ipam/linux.Dockerfile
  azure-ipam/windows.Dockerfile
  cni/linux.Dockerfile
  cni/windows.Dockerfile
  dropgz/build/cniTest_linux.Dockerfile
  dropgz/build/cniTest_windows.Dockerfile
  dropgz/build/windows.Dockerfile
  hack/manifests/cni-installer-v1.yaml
  hack/manifests/cni-installer.yaml
  test/integration/manifests/cilium/cns-write-ovly.yaml
  test/integration/manifests/cni/cni-installer-v1-windows.yaml
  test/integration/manifests/cni/cni-installer-v1.yaml
  test/integration/manifests/cns/daemonset-linux.yaml
  test/integration/manifests/cns/daemonset-windows.yaml
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_create.go
Labels: enhancement, cni, ci, windows, azure-ipam, release/latest, dropgz

#2408 fix: replace nightly params
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
Labels: fix, ci

#2412 ci: Adding the Vnet Scale Integration Tests to the E2E pipeline
  .pipelines/pipeline.yaml
  hack/aks/Makefile
  hack/aks/README.md
Labels: ci, vnet-scale

#2406 ci: CNI Load Test pipeline trigger
  .pipelines/cni/pipeline.yaml
Labels: ci

#2395 fix: block wireserver port 80 traffic in multitenancy
  network/network_linux.go
  network/networkutils/networkutils_linux.go
  network/transparent_vlan_endpointclient_linux.go
Labels: cni, fix, multitenancy

#2249 test(scale): [NPM] fix flakes in kwok and capture kernel state on failure
  .pipelines/npm/npm-scale-test.yaml
  debug/windows/npm/win-debug.sh
  test/scale/connectivity/test-connectivity.sh
  test/scale/run-kwok-as-pod.sh
  test/scale/test-scale.sh
Labels: npm, ci
