Repository Azure/azure-container-networking, pull requests merged in 2024-12, with the labels that each got.

#3226 fix: return error on interface not found and always clean up snat ep
  network/endpoint.go
  network/endpoint_linux.go
  network/manager.go
  network/ovs_endpoint_snatroute_linux.go
  network/snat/snat_linux.go
  network/snat/snat_linux_test.go
  network/transparent_vlan_endpoint_snatroute_linux.go
  network/transparent_vlan_endpointclient_linux.go
  network/transparent_vlan_endpointclient_linux_test.go
Labels: cni, fix, linux, multitenancy

#3263 fix: hardcode CLI for 1.13 agent
  .pipelines/templates/cilium-cli.yaml
Labels: fix, ci, release/1.4

#3264 backport: ci: remove logger field from portforwarder to avoid race with goroutine (#2959)
  test/integration/k8s_test.go
  test/integration/portforward.go
Labels: cni, ci, release/1.4

#3254 fix: save cni state only during endpoint creation or deletion
  cni/network/invoker_azure.go
  network/manager.go
Labels: cni, fix, release/1.4, needs-backport, release/1.5

#3275 disable custom codeql because something is broken
  .github/workflows/codeql.yaml
Labels: fix, ci
