Repository Azure/azure-container-networking, pull requests merged in 2024-07, with the labels that each got.

#2819 fix: update azure-vnet directory permissions
  processlock/processlock.go
Labels: cni, fix, needs-backport

#2822 fix: add hns network id to endpoint struct for pushing to cns in stateless
  network/endpoint_windows.go
  network/manager.go
Labels: fix, swift-v2

#2823 backport: fix: update azure-vnet directory permissions (#2819)
  processlock/processlock.go
Labels: cni, fix, release/1.5

#2820 ci: align cilium charts with AKS
  test/integration/manifests/cilium/v1.13/cilium-config/cilium-config.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset-dualstack.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config-dualstack.yaml
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config-hubble.yaml
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config.yaml
Labels: ci, needs-backport, release/1.5

#2825 feat: add subnet address space to mtpnc status
  crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
Labels: swift-v2

#2826 Fix ACN PR Pipeline failures related to swiftv2
  .pipelines/multitenancy/swiftv2-e2e-step-template.yaml
  .pipelines/pipeline.yaml
  hack/aks/Makefile
  test/integration/manifests/swiftv2/podnetwork.yaml
Labels: needs-backport, release/1.5

#2693 feat: Adding backend interfaces support to CNS
  cns/NetworkContainerContract.go
  cns/configuration/env.go
  cns/middlewares/k8sSwiftV2.go
  cns/middlewares/k8sSwiftV2_linux_test.go
  cns/middlewares/mock/mockClient.go
  cns/restserver/ipam.go
  cns/restserver/ipam_test.go
  cns/restserver/restserver.go
  cns/restserver/util.go
  cns/restserver/util_test.go
  cns/service/main.go
  cns/types/codes.go
  crd/multitenancy/api/v1alpha1/utils.go
  platform/mockexec.go
  platform/osInterface.go
  platform/os_linux.go
  platform/os_windows.go
  platform/os_windows_test.go
Labels: cns

#2824 backport: fix: update azure-vnet directory permissions (#2819)
  processlock/processlock.go
Labels: cni, fix, release/1.4

#2815 ci: Change `release/v1.5` merge queue trigger
  .pipelines/pipeline.yaml
Labels: ci

#2836 deps: bump azidentity from v1.1.0 to v1.6.0
  go.mod
  go.sum
Labels: cni, dependencies, release/1.4

#2831 chore: update cni in dropgz to 1.5.30
  dropgz/build/linux.Dockerfile
  dropgz/build/windows.Dockerfile
Labels: cni, release/1.5

#2827 Add Status to NodeInfo CRD
  crd/multitenancy/api/v1alpha1/nodeinfo.go
  crd/multitenancy/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
Labels: swift-v2

#2828 add prefix length from mtpnc to podipinfo & gatewayip
  cns/middlewares/k8sSwiftV2.go
  cns/middlewares/k8sSwiftV2_linux.go
  cns/middlewares/k8sSwiftV2_linux_test.go
  cns/middlewares/k8sSwiftV2_windows.go
  cns/middlewares/k8sSwiftV2_windows_test.go
  cns/middlewares/mock/mockClient.go
Labels: swift-v2

#2837 ci: Adjust VM usage for CNI Release Test Pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
Labels: ci, needs-backport

#2634 Add swiftv2 middleware support for standalone service fabric scenario (windows)
  cns/api.go
  cns/configuration/configuration.go
  cns/middlewares/k8sSwiftV2.go
  cns/middlewares/standaloneSwiftV2.go
  cns/restserver/ipam.go
  cns/restserver/util.go
  cns/service/main.go
  cns/wireserver/net.go
Labels: cns

#2835 ci: add AzureLinux, rdma and ARM64 release test scenarios for cilium dual stack
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
Labels: ci, needs-backport, release/1.5

#2838 fix nodeInfo schema
  crd/multitenancy/api/v1alpha1/nodeinfo.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
Labels: swift-v2

#2762 add L1VH IB support on CNI
  cni/azure-windows-swift.conflist
  cni/cni.go
  cni/network/invoker_cns.go
  cni/network/invoker_cns_test.go
  cni/network/network.go
  cni/network/network_test.go
  cni/network/network_windows.go
  cni/network/network_windows_test.go
  cnm/network/network_linux_test.go
  common/plugin.go
  ipam/pool.go
  network/endpoint.go
  network/endpoint_windows.go
  network/endpoint_windows_test.go
  network/manager.go
  network/manager_mock.go
  network/network.go
  network/network_test.go
  network/network_windows.go
  network/network_windows_test.go
  testutils/netapi_mock.go
Labels: cni

#2839 Delete hack/manifests/sshd.yaml
  hack/manifests/sshd.yaml
Labels: fix

#2848 [backport] ci: Adjust VM usage for CNI Release Test Pipeline (#2837)
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
Labels: ci, release/1.5

#2847 fix: Revert "refactor: code changes for stateless cni and swift v2 (#2688)" on `release/v1.5`
  cni/network/invoker.go
  cni/network/invoker_azure.go
  cni/network/invoker_azure_test.go
  cni/network/invoker_cns.go
  cni/network/invoker_cns_test.go
  cni/network/invoker_mock.go
  cni/network/multitenancy.go
  cni/network/multitenancy_mock.go
  cni/network/multitenancy_test.go
  cni/network/network.go
  cni/network/network_linux.go
  cni/network/network_linux_test.go
  cni/network/network_test.go
  cni/network/network_windows.go
  cni/network/network_windows_test.go
  cnm/network/network.go
  netio/netio.go
  network/bridge_networkclient_linux.go
  network/endpoint.go
  network/endpoint_linux.go
  network/endpoint_snatroute_linux.go
  network/endpoint_test.go
  network/endpoint_windows.go
  network/endpoint_windows_test.go
  network/manager.go
  network/manager_mock.go
  network/manager_test.go
  network/mock_endpointclient.go
  network/network.go
  network/network_linux.go
  network/network_test.go
  network/network_windows.go
  network/network_windows_test.go
  network/ovs_endpoint_infraroute_linux.go
  network/ovs_endpoint_snatroute_linux.go
  network/ovs_endpointclient_linux.go
  network/secondary_endpoint_client_linux.go
  network/secondary_endpoint_linux_test.go
  network/transparent_vlan_endpoint_snatroute_linux.go
Labels: fix, release/1.5

#2849 fix: CNS should ignore NNCs that are being deleted (#2798)
  cns/kubecontroller/nodenetworkconfig/reconciler.go
  cns/service/main.go
Labels: cns, fix, release/1.4

#2844 test: add ut for populating network and endpoint hns id in endpoint and endpoint info structs
  network/endpoint.go
  network/endpoint_test.go
  network/endpoint_windows_test.go
  network/hnswrapper/hnsv2wrapperfake.go
  network/manager.go
  network/manager_test.go
  network/network.go
  network/network_test.go
  network/network_windows_test.go
Labels: cni, windows

#2850 fix: CNS should ignore NNCs that are being deleted (#2798)
  cns/kubecontroller/nodenetworkconfig/reconciler.go
  cns/service/main.go
Labels: cns, fix, release/1.5

#2861 ci: Cleanup ACN PR pipeline yaml
  .pipelines/pipeline.yaml
Labels: ci

#2863 ci: Unblock nightly pipeline
  .pipelines/cni/cilium/nightly-release-test.yml
Labels: ci

#2843 Add MacAddress to NodeInfo CRD
  crd/multitenancy/api/v1alpha1/nodeinfo.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_nodeinfo.yaml
Labels: swift-v2

#2845 test: validate inputs to acn components
  cni/network/network.go
  cni/network/network_test.go
  cns/NetworkContainerContract.go
  cns/NetworkContainerContract_test.go
Labels: cns, cni

#2862 ci: Shift E2E cluster creation
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
  .pipelines/pipeline.yaml
Labels: ci, release/1.4, needs-backport, release/1.5

#2866 [fix] ci: update cyclonus workflow
  .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
  .github/workflows/cyclonus-netpol-test.yaml
Labels: npm, fix, ci, needs-backport, release/1.5

#2867 ci: Update triggers for NPM pipelines
  .pipelines/npm/npm-conformance-tests-latest-release.yaml
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/npm/npm-scale-test.yaml
Labels: npm, ci

#2868 ci: update Cyclonus workflow triggers
  .github/workflows/cyclonus-netpol-test.yaml
Labels: npm, ci

#2874 ci: [NPM] speed up Windows conformance and disable Windows Cyclonus/Scale
  .pipelines/npm/npm-conformance-tests-latest-release.yaml
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/npm/npm-scale-test.yaml
Labels: npm, ci, windows

#2869 chore: add enable k8s device plugin to cns config
  cns/configuration/configuration.go
Labels: swift-v2

#2864 ci: Remove winio from replace( )
  go.mod
  go.sum
Labels: npm, ci

#2875 ci: [NPM] NPM Conformance Test improvements
  .pipelines/npm/npm-conformance-tests.yaml
Labels: npm, ci

#2841 fix: [NPM] [Linux] race condition when editing NetPol with "except" CIDR
  npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
  npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
Labels: bug, npm, linux

#2876 ci: [NPM] add bash directive to scale scripts
  test/scale/connectivity/test-connectivity.sh
  test/scale/test-scale.sh
Labels: npm, ci

#2852 fix: add ipv6 port policy in addition to ipv4 policy if no host ip and ipv6 enabled
  cni/network/network_windows.go
  cni/network/network_windows_test.go
Labels: cni, fix, windows, needs-backport

#2877 Return error if hns network exists for transparent network
  network/network_windows.go
Labels: cni

#2883 backport: fix: add ipv6 port policy in addition to ipv4 policy if no host ip and ipv6 enabled (#2852)
  cni/network/network_windows.go
  cni/network/network_windows_test.go
Labels: cni, fix, release/1.5

#2882 [backport] fix/ci: Linux NPM race condition editing "except" CIDR and NPM pipeline fixes
  .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
  .github/workflows/cyclonus-netpol-test.yaml
  .pipelines/npm/npm-conformance-tests-latest-release.yaml
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/npm/npm-scale-test.yaml
  npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
  npm/pkg/dataplane/ipsets/ipsetmanager_linux_test.go
  test/scale/connectivity/test-connectivity.sh
  test/scale/test-scale.sh
Labels: npm, ci, linux

#2888 ci: make lint target release/v1.5 branch
  .github/workflows/golangci.yaml
Labels: ci, release/1.5

#2857 fetch primary mac for hns accelnet
  cns/middlewares/k8sSwiftV2.go
  cns/restserver/internalapi.go
  cns/restserver/internalapi_linux.go
  cns/restserver/internalapi_windows.go
  cns/service/main.go
Labels: cns, swift-v2
