Repository Azure/azure-container-networking, pull requests merged in 2024-04, with the labels that each got.

#2660 fix: Using Node IP as the primary IP allowing the use of all the IPs in the subnet for pods in Vnet Scale Mode and added the fix for Vnet Scale Cillium
  cns/kubecontroller/nodenetworkconfig/conversion.go
  cns/kubecontroller/nodenetworkconfig/conversion_linux.go
  cns/kubecontroller/nodenetworkconfig/conversion_linux_test.go
Labels: cns, vnet-scale

#2669 chore: update the cilium nightly config
  test/integration/manifests/cilium/cilium-config-hubble.yaml
  test/integration/manifests/cilium/cilium-nightly-config.yaml
Labels: ci

#2682 fix: Prevent iptable list cmd to do reverse dns lookup
  iptables/iptables.go
Labels: cni, fix, release/1.4, release/latest, needs-backport

#2668 ETW logging implementation in CNI
  cni/log/logger.go
  cni/log/logger_linux.go
  cni/log/logger_windows.go
  zapetw/core_windows.go
Labels: cni, logging

#2686 fix: Added -n option in iptables list cmd to prevent reverse dns lookup
  iptables/iptables.go
Labels: cni, fix

#2681 ci: Remove path filter from PR pipeline CI triggers
  .pipelines/pipeline.yaml
Labels: ci

#2705 ci: Remove AKS Engine storage account usage
  .pipelines/pipeline.yaml
Labels: ci, needs-backport

#2707 ci: Updating k8s test suite for NPM to latest
  .pipelines/cni/pipeline.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
  .pipelines/npm/npm-conformance-tests.yaml
Labels: npm, ci

#2523 feat: Modifying stateless CNI state to account for swift 2.0 changes.
  Makefile
  cns/api.go
  cns/client/client.go
  cns/client/client_test.go
  cns/restserver/ipam.go
  cns/restserver/restserver.go
  network/manager.go
Labels: cni

#2700 Feat: Added ETW logging support for CNS.
  cns/logger/cnslogger.go
  cns/logger/cnslogger_linux.go
  cns/logger/cnslogger_windows.go
  cns/service/main.go
Labels: cns, logging

#2706 ci: [backport] Remove AKS Engine storage account usage
  .pipelines/pipeline.yaml
Labels: ci, release/1.4

#2711 fix: close connection on any return from azure-vnet-telemetry
  telemetry/telemetrybuffer.go
Labels: fix, telemetry

#2650 Start two CNS servers with different handlers
  cnm/ipam/ipam.go
  cnm/network/network.go
  cnm/plugin.go
  cns/common/service.go
  cns/restserver/api.go
  cns/restserver/api_test.go
  cns/restserver/ipam.go
  cns/restserver/restserver.go
  cns/restserver/util.go
  cns/restserver/v2/server.go
  cns/restserver/v2/server_test.go
  cns/service.go
  cns/service/main.go
  common/config.go
  common/listener.go
Labels: cns
