Repository Azure/azure-container-networking, pull requests merged in 2024-11, with the labels that each got.

#3098 [backport] ci: Update Cilium image usage for release/v1.5
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/networkobservability/pipeline.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/templates/cilium-cli.yaml
  test/integration/manifests/cilium/daemonset.yaml
  test/integration/manifests/cilium/deployment.yaml
  test/integration/manifests/cilium/v1.12/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.12/cilium-operator/templates/deployment.yaml
  test/integration/manifests/cilium/v1.13/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.13/cilium-operator/templates/deployment.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset-dualstack.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
Labels: ci, release/1.5

#3097 ci: Update Cilium image usage for release/v1.4
  .pipelines/cni/cilium/cilium-cni-load-test.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  test/integration/manifests/cilium/daemonset.yaml
  test/integration/manifests/cilium/deployment.yaml
Labels: ci, release/1.4

#3073 feat: support for cilium + nodesubnet
  cns/fakes/nmagentclientfake.go
  cns/restserver/helper_for_nodesubnet_test.go
  cns/restserver/nodesubnet.go
  cns/restserver/nodesubnet_test.go
  cns/restserver/restserver.go
  cns/service/main.go
Labels: cns, go

#3095 fix: pass ai metadata to telemetry during cni image build
  Makefile
  cni/Dockerfile
  cni/telemetry/service/telemetrymain.go
  cns/service/main.go
  telemetry/aiwrapper_test.go
Labels: cni, fix, ci, telemetry, needs-backport, logging

#3083 test: pipeline changes for cilium nodesubnet
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-step-template.yaml
  hack/aks/Makefile
  hack/aks/README.md
  test/integration/cilium-nodesubnet/ipconfigupdate.go
  test/integration/manifests/ip-masq-agent/config-custom.yaml
  test/integration/manifests/ip-masq-agent/config-reconcile.yaml
Labels: cns, ci

#3050 feat: add IPConfig state logs/metrics to Request/Release handlers
  cns/restserver/internalapi.go
  cns/restserver/ipam.go
  cns/restserver/ipusage.go
  cns/restserver/metrics.go
Labels: cns

#3108 fix: add retraction of v1.16.15
  go.mod
Labels: bug, fix

#3090 fix: [NPM] [Linux] improve iptables version detection and cleanup
  npm/iptm/iptm_test.go
  npm/pkg/dataplane/dataplane_linux.go
  npm/pkg/dataplane/dataplane_linux_test.go
  npm/pkg/dataplane/dataplane_test.go
  npm/pkg/dataplane/parse/parser_test.go
  npm/pkg/dataplane/policies/chain-management_linux.go
  npm/pkg/dataplane/policies/chain-management_linux_test.go
  npm/pkg/dataplane/policies/policymanager_test.go
  npm/pkg/dataplane/policies/testutils_linux.go
  npm/pkg/dataplane/policies/testutils_windows.go
  npm/util/const.go
  npm/util/ioutil/current-azure-chains_test.go
Labels: npm, linux, release/latest, needs-backport

#3110 [backport] fix: [NPM] [Linux] improve iptables version detection and cleanup
  npm/iptm/iptm_test.go
  npm/pkg/dataplane/dataplane_linux.go
  npm/pkg/dataplane/dataplane_linux_test.go
  npm/pkg/dataplane/dataplane_test.go
  npm/pkg/dataplane/parse/parser_test.go
  npm/pkg/dataplane/policies/chain-management_linux.go
  npm/pkg/dataplane/policies/chain-management_linux_test.go
  npm/pkg/dataplane/policies/policymanager_test.go
  npm/pkg/dataplane/policies/testutils_linux.go
  npm/pkg/dataplane/policies/testutils_windows.go
  npm/util/const.go
  npm/util/ioutil/current-azure-chains_test.go
Labels: npm, linux

#3111 [backport] ci: hardcode docker container build image
  Makefile
Labels: ci

#3115 ci: update regex for new cilium images
  .pipelines/templates/cilium-cli.yaml
Labels: ci, release/1.4, release/latest, release/1.5

#3114 [backport] ci: hardcode docker container build image into release/v1.4
  Makefile
Labels: ci, release/1.4

#3118 [forwardport] ci: update regex for new cilium images (#3115)
  .pipelines/templates/cilium-cli.steps.yaml
  .pipelines/templates/cilium-cli.yaml
Labels: ci, release/latest

#3124 ci: standardize E2E job timeout to 2 hours on PR pipeline
  .pipelines/singletenancy/aks/aks-e2e.jobs.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay-stateless/azure-cni-overlay-stateless-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.jobs.yaml
  .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-job-template.yaml
Labels: ci, release/1.4, release/latest, needs-backport, release/1.5

#3131 feat: use proto in CNS usage of client-go
  cns/service/main.go
Labels: enhancement, cns

#3085 feat: adding stateless CNI support for ACI
  cns/restserver/ipam.go
  cns/restserver/ipam_test.go
Labels: cns, cni

#3113 Remove l2bridge checker on windows and l2tunnel mode
  cni/azure-windows-swift-overlay-dualstack.conflist
  cni/azure-windows-swift-overlay.conflist
  cni/azure-windows-swift.conflist
  cns/hnsclient/hnsclient_windows.go
  cns/service/main.go
  network/network_windows.go
  network/network_windows_test.go
Labels: cni

#3105 feat: Windows HPC base image
  .pipelines/cni/pipeline.yaml
  .pipelines/containers/container-template.steps.yaml
  .pipelines/containers/container-template.yaml
  .pipelines/containers/manifest-template.steps.yaml
  .pipelines/containers/manifest-template.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
  .pipelines/npm/npm-conformance-tests-latest-release.yaml
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/npm/npm-cyc-win-tests-latest-release.yaml
  .pipelines/npm/npm-scale-test.yaml
  .pipelines/pipeline.yaml
  .pipelines/run-pipeline.yaml
  Makefile
  azure-ipam/Dockerfile
  cni/Dockerfile
  cns/Dockerfile
  npm/windows.Dockerfile
Labels: enhancement, windows, release/latest, needs-backport

#3125 ci: Add exit code capture for PR pipeline
  .pipelines/singletenancy/aks-swift/aks-swift-e2e.steps.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/aks/aks-e2e.steps.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-nodesubnet/cilium-nodesubnet-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e.steps.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e.steps.yaml
  .pipelines/templates/cilium-cli.steps.yaml
  .pipelines/templates/cilium-cli.yaml
  .pipelines/templates/cilium-tests.yaml
Labels: ci, release/latest, needs-backport, release/1.5

#3109 Fix: Add default route on delegatedNIC interface
  cns/middlewares/k8sSwiftV2.go
  cns/middlewares/k8sSwiftV2_linux.go
  cns/middlewares/k8sSwiftV2_windows.go
  cns/middlewares/k8sSwiftV2_windows_test.go
Labels: cns

#3137 [backport] ci: standardize E2E job timeout to 2 hours on PR pipeline (#3124)
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-job-template.yaml
Labels: ci, release/1.5

#3126 [backport] ci: PR pipeline yaml cleanup
  .pipelines/pipeline.yaml
  .pipelines/templates/delete-cluster.yaml
Labels: ci, release/1.5

#3139 [backport] fix: Add --kubernetes-version to linux-cniv1-up cluster creation (#2952)
  hack/aks/Makefile
Labels: fix, ci, release/1.5

#3141 test: add create endpoint info policy test
  cni/network/network_windows_test.go
Labels: cni, ci

#2993 fix: remove PowerShell from Windows registry interactions
  cns/service/main.go
  platform/os_linux.go
  platform/os_windows.go
  platform/os_windows_test.go
  test/validate/validate.go
Labels: cns, fix, release/latest, needs-backport

#3132 backport: fix: pass ai metadata to telemetry during cni image build (#3095)
  Makefile
  cni/linux.Dockerfile
  cni/telemetry/service/telemetrymain.go
  cni/windows.Dockerfile
  cns/service/main.go
  telemetry/aiwrapper_test.go
Labels: cni, fix, ci, telemetry, logging, release/1.5

#3135 Remove bridgeName field from CNI windows conflist files
  cni/azure-windows-multitenancy.conflist
  cni/azure-windows-swift-overlay-dualstack.conflist
  cni/azure-windows-swift-overlay.conflist
  cni/azure-windows-swift.conflist
  cni/azure-windows.conflist
Labels: cni

#3148 chore: update some dependencies in 1.5
  go.mod
  go.sum
Labels: dependencies

#3154 chore: update dependencies in 1.4
  go.mod
  go.sum
Labels: dependencies

#3153 ci: disable swiftv2 E2E
  .pipelines/pipeline.yaml
  .pipelines/run-pipeline.yaml
Labels: ci, swift-v2, release/latest, needs-backport, release/1.5

#3158 ci: add coverage from #3089 to hubble testing in CNI Release Test Pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Labels: ci

#3140 [CNS] add config snapshot event metrics at an interval
  cns/configuration/cns_config.json
  cns/configuration/configuration.go
  cns/configuration/configuration_test.go
  cns/configuration/testdata/good.json
  cns/logger/constants.go
  cns/metric/configsnapshot.go
  cns/metric/configsnapshot_test.go
  cns/service/main.go
Labels: cns, telemetry

#3142 use cns logger lib
  cns/service/main.go
Labels: cns

#3162 [fix] ci: update recover resource job
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
Labels: fix, ci, release/latest, needs-backport, release/1.5

#3166 chore: add release branches to dependabot gomod updates
  .github/dependabot.yaml
Labels: ci

#3161 test: [NPM] fix windows unit test for policymanager
  npm/pkg/dataplane/policies/policymanager_test.go
Labels: npm

#3206 ci: update dependabot labels
  .github/dependabot.yaml
Labels: ci

#3165 fix: remove PowerShell from Windows registry interactions (#2993)
  cns/service/main.go
  platform/os_linux.go
  platform/os_windows.go
  platform/os_windows_test.go
Labels: enhancement, cns, release/1.5
