Repository Azure/azure-container-networking, pull requests merged in 2024-01, with the labels that each got.

#2460 ci: Add workflow check for Merge Queue pipeline start on Azure Pipeline
  .github/workflows/pipeline.yaml
Labels: ci

#2464 fix: check for notStarted
  .github/workflows/pipeline.yaml
Labels: fix

#2425 ci: add date to cilium nightly cluster name
  .pipelines/cni/cilium/nightly-release-test.yml
Labels: ci

#2348 ci: Add k8s conformance tests to Cilium CI/CD
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
Labels: ci

#2480 ci: Increase ACN pipeline Swift E2E vmSize
  .pipelines/pipeline.yaml
Labels: ci

#2487 ci:[CNI] Remove load balancer tests and add rollout status for konnec…
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/cni/k8s-e2e/k8s-e2e-step-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
Labels: ci, release/1.4

#2482 ci: Cleanup Dual OS ACN PR pipeline step templates
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
  .pipelines/templates/log-template.yaml
Labels: ci

#2450 backport: fix: add contexts to clean up fsnotify goroutines
  cns/fsnotify/fsnotify.go
  cns/service/main.go
  go.mod
  go.sum
Labels: release/1.4

#2497 ci: increase dependabot PR limit to 10
  .github/dependabot.yaml
Labels: enhancement, ci

#2489 ci: constrain cilium to linux on Release Test Pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Labels: ci

#2498 ci: Improve CNI|NPM integration test
  .pipelines/npm/npm-cni-integration-test.yaml
Labels: npm, cni, ci

#2481 ci: verbose output for make test-load
  Makefile
Labels: ci

#2484 ci: Improve TestValidateState calls from load package
  test/integration/load/load_test.go
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_get.go
Labels: ci

#2490 ci: add OS scale timeout
  test/integration/load/load_test.go
Labels: ci

#2496 ci: add kubeproxy restart before windows k8s conformance testing
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
Labels: ci

#2505 fix: downgrade k8s components to 1.28
  go.mod
  go.sum
Labels: dependencies

#2352 fix: lint vs release branch instead of master
  Makefile
Labels: ci, release/1.4

#2537 feat: add imds client
  cns/imds/client.go
  cns/imds/client_test.go
  cns/imds/testdata/computeMetadata.json
Labels: cns, swift-v2

#2453 Update Go and deps on v1.4 branch
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/crdgen.yaml
  .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
  .github/workflows/cyclonus-netpol-test.yaml
  .github/workflows/golangci.yaml
  azure-ipam/go.mod
  azure-ipam/go.sum
  build/tools/go.mod
  cni/build/windows.Dockerfile
  cns/linux.Dockerfile
  cns/windows.Dockerfile
  dropgz/build/cniTest_linux.Dockerfile
  dropgz/build/cniTest_windows.Dockerfile
  dropgz/go.mod
  go.mod
  go.sum
  hack/toolbox/Dockerfile.windows
  hack/toolbox/server/Dockerfile.heavy
  hack/toolbox/server/Dockerfile.lite
  npm/linux.Dockerfile
  npm/windows.Dockerfile
  tools/acncli/Dockerfile
  zapai/go.mod
Labels: release/1.4

#2545 feat: create or update nodeinfo crd at cns startup for multitenancy
  cns/service/main.go
  crd/multitenancy/client.go
  crd/multitenancy/client_test.go
Labels: cns, swift-v2

#2485 ci: Improve Validate package
  test/integration/datapath/datapath_windows_test.go
  test/internal/kubernetes/utils.go
  test/validate/linux_validate.go
  test/validate/utils.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: ci

#2535 Add new status to PN CRD
  crd/multitenancy/api/v1alpha1/podnetwork.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
Labels: swift-v2

#2422 feat: v2 swift ipampool
  cns/api.go
  cns/configuration/configuration.go
  cns/fakes/cnsfake.go
  cns/ipampool/metrics.go
  cns/ipampool/monitor.go
  cns/ipampool/v2/adapter.go
  cns/ipampool/v2/math_test.go
  cns/ipampool/v2/monitor.go
  cns/ipampool/v2/monitor_test.go
  cns/kubecontroller/pod/reconciler.go
  cns/restserver/ipam.go
  cns/service/main.go
  go.mod
  test/integration/manifests/cnsconfig/swiftconfigmap.yaml
Labels: cns, swift, release/latest

#2463 ci: Replace make test-intergration within ACN PR pipeline
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
Labels: ci

#2553 ci: nsenter daemonset
  test/integration/manifests/load/privileged-daemonset.yaml
  test/validate/linux_validate.go
Labels: ci

#2554 ci: Replace make test-integration [2/2]
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
Labels: ci
