Repository Azure/azure-container-networking, pull requests merged in 2024-05, with the labels that each got.

#2719 backport: fix: close connection on any return from azure-vnet-telemetry (#2711)
  telemetry/telemetrybuffer.go
Labels: fix, telemetry, release/1.4

#2724 ci: match cilium ds cluster create/delete
  .pipelines/cni/pipeline.yaml
Labels: ci

#2717 feat: update CRDs to accomodate multiple pod nics
  crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenancy/api/v1alpha1/podnetwork.go
  crd/multitenancy/api/v1alpha1/podnetworkinstance.go
  crd/multitenancy/api/v1alpha1/zz_generated.deepcopy.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworkinstances.yaml
  crd/multitenancy/manifests/multitenancy.acn.azure.com_podnetworks.yaml
Labels: swift-v2

#2726 chore: update cni in dropgz to 1.5.28
  dropgz/build/linux.Dockerfile
  dropgz/build/windows.Dockerfile
Labels: cni, dropgz

#2727 ci: Change ACR Service Connection
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/containers/container-template.yaml
  .pipelines/containers/manifest-template.yaml
Labels: ci

#2722 feat: Adding MACAddress to CNS endpoint State and refactoring stateless CNI code
  cni/windows.Dockerfile
  cns/cnireconciler/podinfoprovider.go
  cns/restserver/ipam.go
  cns/restserver/restserver.go
  network/endpoint.go
  network/endpoint_windows.go
  network/manager.go
Labels: cns

#2725 ci: test async delete in cilium stages
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  azure-ipam/go.mod
  azure-ipam/ipam.go
  hack/scripts/async-delete-test.sh
Labels: ci

#2736 ci: create template for cilium cli install
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/templates/cilium-cli.yaml
Labels: ci

#2740 ci: adding a retry login on exec cmd on failure
  test/internal/kubernetes/utils.go
Labels: ci

#2742 fix: pin Windows images
  cns/windows.Dockerfile
  npm/windows.Dockerfile
Labels: fix, ci

#2743 fix: order of healthz and readyz arguments
  cns/healthserver/server.go
Labels: cns, fix

#2746 feat: plumb accelnet bool through interfaceinfo
  crd/multitenancy/api/v1alpha1/multitenantpodnetworkconfig.go
  crd/multitenancy/manifests/multitenancy.acn.azure.com_multitenantpodnetworkconfigs.yaml
Labels: cns, swift-v2

#2704 ci: Remove merge queue workflow
  .github/workflows/pipeline.yaml
Labels: ci

#2749 ci: skip no-unexpected-packet-drops for cilium dualstack e2e
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
Labels: ci

#2754 Add gRPC Protobuf Files for CNS Operations
  Makefile
  cns/grpc/proto/server.proto
  cns/grpc/v1alpha/server.pb.go
  cns/grpc/v1alpha/server_grpc.pb.go
Labels: cns
