Repository Azure/azure-container-networking, pull requests merged in 2024-09, with the labels that each got.

#2983 Add join VNET call for every AZR NC unpublish call
  cns/restserver/api.go
Labels: AZR

#2970 fix: add legacy IPAM metrics back to IPAMv2
  cns/ipampool/metrics/metrics.go
  cns/ipampool/metrics/observer.go
  cns/ipampool/monitor.go
  cns/ipampool/v2/monitor.go
  cns/service/main.go
  crd/clustersubnetstate/client.go
Labels: cns, swift, fix, release/latest

#2975 backport: ci: remove logger field from portforwarder to avoid race with goroutine (#2959)
  test/e2e/framework/kubernetes/port-forward.go
  test/integration/datapath/datapath_linux_test.go
  test/integration/k8s_test.go
  test/integration/networkobservability/hubble_test.go
  test/integration/portforward.go
Labels: cni, fix, ci, release/1.5

#2989 fix: add dhcp discover packet to linux swiftv2 to ensure mappings exist for dns
  cni/network/network.go
  dhcp/dhcp_linux.go
  dhcp/dhcp_windows.go
  network/dhcp.go
  network/endpoint.go
  network/endpoint_linux.go
  network/endpoint_test.go
  network/endpoint_windows.go
  network/endpoint_windows_test.go
  network/manager.go
  network/secondary_endpoint_client_linux.go
  network/secondary_endpoint_linux_test.go
Labels: cni, fix, linux, swift-v2

#2990 fix: [Linux] [NPM] handle #2977 for netpols without cidrs
  .gitignore
  npm/pkg/dataplane/dataplane.go
  npm/pkg/dataplane/ipsets/ipsetmanager.go
Labels: bug, npm, linux

#3007 [backport] fix: [NPM] [Linux] handle more than 15 leaked ipsets
  npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
Labels: npm, linux

#2986 [fix] ci: cluster deletion for swiftv2
  .pipelines/pipeline.yaml
  .pipelines/templates/delete-cluster.yaml
Labels: fix, ci, release/latest, needs-backport, release/1.5

#3011 ci: Unblock k8s 1.30 | ACN v1.6 testing
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
Labels: ci, release/latest

#2968 ci: add delay after link creation for test add remove static arp
  netlink/netlink_test.go
Labels: cni, fix, ci

#3016 Add join VNET call for every AZR NC unpublish call with fixed UTs
  cns/restserver/api.go
  cns/restserver/api_test.go
Labels: AZR

#3018 fix: Add missing service connection
  .pipelines/cni/cilium/nightly-release-test.yml
Labels: fix, ci

#2924 fix: update default k8s ver to 1.30
  .pipelines/pipeline.yaml
  hack/aks/Makefile
Labels: cns, cni, release/latest

#3012 ci: add cilium 1.16
  test/integration/manifests/cilium/v1.16/cilium-agent/files/clusterrole.yaml
  test/integration/manifests/cilium/v1.16/cilium-agent/files/clusterrolebinding.yaml
  test/integration/manifests/cilium/v1.16/cilium-agent/files/serviceaccount.yaml
  test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset-dualstack.yaml
  test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.16/cilium-config/cilium-config-dualstack.yaml
  test/integration/manifests/cilium/v1.16/cilium-config/cilium-config-hubble.yaml
  test/integration/manifests/cilium/v1.16/cilium-config/cilium-config.yaml
  test/integration/manifests/cilium/v1.16/cilium-operator/files/clusterrole.yaml
  test/integration/manifests/cilium/v1.16/cilium-operator/files/clusterrolebinding.yaml
  test/integration/manifests/cilium/v1.16/cilium-operator/files/serviceaccount.yaml
  test/integration/manifests/cilium/v1.16/cilium-operator/templates/deployment.yaml
  test/integration/manifests/cilium/v1.16/hubble/hubble-peer-svc.yaml
Labels: ci

#3017 Add support in CNS NMAgent Client to fetch secondary IPs
  cns/nodesubnet/helper_for_ip_fetcher_test.go
  cns/nodesubnet/ip_fetcher.go
  cns/nodesubnet/ip_fetcher_test.go
  nmagent/client.go
  nmagent/client_test.go
  nmagent/ipaddress.go
  nmagent/macaddress.go
  nmagent/requests.go
  nmagent/requests_test.go
  nmagent/responses.go
Labels: cns, go

#2973 ci: add create cluster stage to cilium scale test pipeline
  .pipelines/cni/cilium/cilium-scale-test.yaml
Labels: ci

#3024 ci: add timeoutInMinutes during scale
  .pipelines/cni/cilium/cilium-scale-test.yaml
Labels: ci

#2967 fix: Handle async delete in stateless cni
  cni/network/network.go
  cns/client/client.go
  cns/configuration/configuration.go
  cns/endpointmanager/endpointmanager.go
  cns/endpointmanager/endpointmanager_linux.go
  cns/endpointmanager/endpointmanager_windows.go
  cns/fsnotify/fsnotify.go
  cns/hnsclient/hnsclient_windows.go
  cns/restserver/ipam.go
  cns/service/main.go
  cns/types/codes.go
  network/errors.go
  network/manager.go
Labels: cns, cni, ci

#2914 feat: adding stateless CNI pipeline test
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/azure-cni-overlay-stateless/azure-cni-overlay-stateless-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay-stateless/azure-cni-overlay-stateless-e2e-step-template.yaml
  test/integration/manifests/cnsconfig/azurestatelesscnioverlaywindowsconfigmap.yaml
  test/internal/kubernetes/utils_create.go
  test/validate/linux_validate.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: cni

#3020 Default to accelnet behavior in CNI for SwiftV2 windows
  cni/network/invoker_cns.go
  cni/network/invoker_cns_test.go
  cni/network/invoker_mock.go
  cni/network/multitenancy_test.go
  cni/network/network.go
  cni/network/network_test.go
  cni/network/network_windows.go
  cni/network/network_windows_test.go
  cns/middlewares/k8sSwiftV2.go
  cns/middlewares/k8sSwiftV2_linux.go
  cns/middlewares/k8sSwiftV2_linux_test.go
  network/endpoint_test.go
  network/endpoint_windows.go
  network/endpoint_windows_test.go
  network/manager_test.go
  network/network_windows.go
  network/network_windows_test.go
Labels: windows, swift-v2

#3025 fix: HTTPRemoteRestService config missing Direct ChannelMode
  cns/service/main.go
Labels: bug, cns

#3035 [ci] fix: CNI-LSG pipeline cluster deletion
  .pipelines/cni/lsg/pipeline.yaml
Labels: fix, ci

#3036 Update go toolchain to cover cve CVE-2024-34156
  go.mod
Labels: cns

#3032 chore: rip out dropgz
  .pipelines/pipeline.yaml
  .pipelines/run-pipeline.yaml
  Makefile
  dropgz/build/linux.Dockerfile
  dropgz/build/windows.Dockerfile
Labels: release/latest, dropgz

#2871 backport: migrate from dropgz to azure-cni, azure-ipam
  .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/submodules-pipeline.yaml
  Makefile
  azure-ipam/go.mod
  azure-ipam/go.sum
  azure-ipam/linux.Dockerfile
  azure-ipam/windows.Dockerfile
  cni/linux.Dockerfile
  cni/windows.Dockerfile
  hack/aks/Makefile
  test/integration/manifests/cni/cni-installer-v1-windows.yaml
  test/integration/manifests/cni/cni-installer-v1.yaml
  test/integration/manifests/cni/cni-installer.yaml
  test/integration/manifests/cni/manager.yaml
  test/integration/manifests/cns/daemonset.yaml
  test/integration/setup_test.go
Labels: cni, swift, ci, release/1.4, exempt-stale
