Repository Azure/azure-container-networking, pull requests merged in 2024-02, with the labels that each got.

#2418 ci:Adding cilium dualstack overlay pipeline steps
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  test/integration/manifests/cilium/cilium-config-dualstack.yaml
  test/validate/linux_validate.go
Labels: ci

#2560 fix: az pipeline output within Merqe Queue Check
  .github/workflows/pipeline.yaml
Labels: fix, ci

#2561 chore: [NPM] Remove TLS Certifications in NPM
  .gitignore
  npm/linux.Dockerfile
  npm/scripts/generate_certs.sh
  npm/scripts/san.cnf
Labels: npm, linux

#2515 fix: block pod to wireserver port 80 traffic on windows multitenancy
  cni/azure-windows-multitenancy.conflist
Labels: cni, fix, windows, multitenancy

#2558 Cilium Load Test with Hubble Enabled.
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
  test/integration/manifests/cilium/cilium-config-hubble.yaml
Labels: ci

#2566 fix: build imds compute url correctly and give a default retryAttempts
  cns/imds/client.go
  cns/imds/client_test.go
Labels: cns, swift-v2

#2279 ci: Add Windows CNIv2 to CNI Load Test Pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/load-test-templates/restart-cns-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
  .pipelines/templates/create-cluster.yaml
  .pipelines/templates/log-template.yaml
  hack/aks/Makefile
  test/integration/load/load_test.go
  test/integration/load/setup_test.go
  test/integration/manifests/cns/daemonset-windows.yaml
  test/integration/manifests/cnsconfig/swiftlinuxconfigmap.yaml
  test/integration/manifests/cnsconfig/swiftwindowsconfigmap.yaml
  test/internal/kubernetes/utils_create.go
Labels: ci

#2470 feat: Migration stateless cni
  cni/linux.Dockerfile
  cns/cnireconciler/podinfoprovider.go
  cns/cnireconciler/podinfoprovider_test.go
  cns/configuration/configuration.go
  cns/restserver/ipam.go
  cns/service/main.go
  network/endpoint.go
  network/endpoint_linux.go
  network/endpoint_windows.go
  network/manager.go
  network/manager_mock.go
Labels: cni

#2570 fix: modify cnms dockerfile with new image
  cnms/Dockerfile
Labels: fix

#2444 Enable CNS swiftv2 path for SF/Standalone scenario to program secondary nics
  cns/NetworkContainerContract.go
  cns/api.go
  cns/client/client.go
  cns/client/client_test.go
  cns/configuration/configuration.go
  cns/hnsclient/hnsclient_windows.go
  cns/restserver/SFSwiftV2.go
  cns/restserver/cnsclient_test.go
  cns/restserver/internalapi.go
  cns/restserver/ipam.go
  cns/restserver/ipam_test.go
  cns/restserver/k8sSwiftV2.go
  cns/restserver/k8sSwiftV2_test.go
  cns/restserver/restserver.go
  cns/restserver/util.go
  cns/service/main.go
  cns/wireserver/client.go
  cns/wireserver/net.go
Labels: cns

#2546 ci: Capture privileged pod failure
  .pipelines/templates/log-template.yaml
Labels: ci

#2562 ci: parameterize cilium 1.14 templates
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/networkobservability/pipeline.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/files/clusterrole.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/files/clusterrolebinding.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/files/serviceaccount.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.tpl
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config-dualstack.yaml
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config-hubble.yaml
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/files/clusterrole.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/files/clusterrolebinding.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/files/serviceaccount.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.tpl
  test/integration/manifests/cilium/v1.14/hubble/hubble-peer-svc.yaml
Labels: ci

#2582 chore: create directory for cilium 1.12 templates
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/networkobservability/pipeline.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  test/integration/manifests/cilium/v1.12/cilium-agent/files/clusterrole.yaml
  test/integration/manifests/cilium/v1.12/cilium-agent/files/clusterrolebinding.yaml
  test/integration/manifests/cilium/v1.12/cilium-agent/files/serviceaccount.yaml
  test/integration/manifests/cilium/v1.12/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.12/cilium-config/cilium-config-dualstack.yaml
  test/integration/manifests/cilium/v1.12/cilium-config/cilium-config.yaml
  test/integration/manifests/cilium/v1.12/cilium-operator/files/clusterrole.yaml
  test/integration/manifests/cilium/v1.12/cilium-operator/files/clusterrolebinding.yaml
  test/integration/manifests/cilium/v1.12/cilium-operator/files/serviceaccount.yaml
  test/integration/manifests/cilium/v1.12/cilium-operator/templates/deployment.yaml
Labels: ci

#2590 ci: Replace k8s conformance tests within aks-swift CI
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
Labels: ci, needs-backport

#2593 fix: no longer use pip and keyring for az devops login
  .github/workflows/pipeline.yaml
Labels: fix

#2564 fix: test v1.5 train on k8s 1.28
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/templates/create-cluster.yaml
  hack/aks/Makefile
  test/integration/manifests/cni/cni-installer-v1-windows.yaml
  test/integration/manifests/cns/daemonset-windows.yaml
Labels: ci

#2589 chore: [NPM] Updated NPM to Not Share Host's UTS Namespace + Image/Configmap Alignment with Prod
  .github/workflows/cyclonus-netpol-test.yaml
  npm/azure-npm.yaml
  test/kind/kind.yaml
Labels: npm, linux

#2591 fix: remove unsupported targets when building all binaries
  Makefile
Labels: cni, fix

#2588 fix: fixing CNS IP releae for azure CNI in case of managed endpoint s…
  cns/NetworkContainerContract.go
  cns/restserver/ipam.go
  cns/service/main.go
Labels: cni

#2552 ci: Kernel Upgrade Script
  hack/scripts/cluster-kernel-upgrade.sh
  hack/scripts/kernel-upgrade.sh
Labels: ci

#2577 fix: delete endpoint on cni state save failure
  network/manager.go
Labels: cni, fix

#2592 fix: remove cnms code
  Makefile
  cnms/Dockerfile
  cnms/cnmspackage/api.go
  cnms/cnmspackage/monitor2rules_linux.go
  cnms/service/networkmonitor.go
  cnms/service/networkmonitor_linux_test.go
  network/manager.go
  network/manager_mock.go
  network/monitor_linux.go
  network/monitor_windows.go
Labels: fix

#2598 chore: [NPM] Updated NPM to Not Use Privileged containers and to Mount Container's Root Filesystem as Read Only
  npm/azure-npm.yaml
Labels: npm, linux

#2605 ci: add trigger:none to ACN Network Observability E2E pipeline
  .pipelines/networkobservability/e2e.yaml
Labels: ci
