Repository Azure/azure-container-networking, pull requests merged in 2024-03, with the labels that each got.

#2609 ci: Backport CI dependency changes
  .pipelines/cni/cilium/cilium-cni-load-test.yaml
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/cni/k8s-e2e/k8s-e2e-job-template.yaml
  .pipelines/cni/k8s-e2e/k8s-e2e-step-template.yaml
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/load-test-templates/pod-deployment-template.yaml
  .pipelines/cni/load-test-templates/restart-node-template.yaml
  .pipelines/cni/load-test-templates/validate-state-template.yaml
  .pipelines/cni/singletenancy/windows-cni-load-test-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-step-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-job-template.yaml
  .pipelines/singletenancy/cilium/cilium-e2e-step-template.yaml
  .pipelines/submodules-pipeline.yaml
  .pipelines/templates/create-cluster.yaml
  .pipelines/templates/delete-cluster.yaml
  hack/aks/Makefile
  hack/aks/README.md
  test/internal/k8sutils/utils.go
Labels: ci, release/1.4

#2580 ci: Add Windows2019 to CNI Release Test pipeline
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
Labels: ci

#2618 ci: Add safeguards to prevent race condition resulting from MustRestartDaemonset()
  test/internal/kubernetes/utils.go
Labels: ci

#2603 ci: cilium dualstack for load test pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/networkobservability/pipeline.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  test/integration/manifests/cilium/v1.14/cilium-agent/templates/daemonset.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
Labels: ci

#2621 fix: remove pool monitor from debug api response
  cns/client/client_test.go
  cns/cmd/cli/cli.go
  cns/restserver/api_test.go
  cns/restserver/internalapi_test.go
  cns/restserver/ipam.go
  cns/restserver/ipam_test.go
  cns/restserver/restserver.go
Labels: cns, fix

#2614 fix: backport remove unsupported artifacts
  Makefile
Labels: release/1.4

#2622 ci: update NPM Windows daemonset for k8s version 1.28
  .pipelines/npm/npm-cni-integration-test.yaml
  npm/examples/windows/azure-npm.yaml
Labels: npm, ci

#2636 deps: update controller-runtime
  go.mod
  go.sum
Labels: dependencies

#2637 ci: update Linux CNS dockerfile
  cns/linux.Dockerfile
Labels: cns, ci, needs-backport

#2645 ci: Increase Codeql timeout
  .github/workflows/codeql.yaml
Labels: ci

#2551 ci: Add CNI | LSG Integration Pipeline
  .pipelines/cni/lsg/kernel-upgrade-template.yaml
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/cni/lsg/pipeline.yaml
  test/internal/kubernetes/utils_create.go
Labels: ci

#2642 chore: remove redundant logs
  cni/network/invoker_cns.go
  cni/network/network.go
  network/endpoint.go
  network/endpoint_linux.go
  network/network_linux.go
  network/networkutils/networkutils_linux.go
  network/snat/snat_linux.go
  network/transparent_endpointclient_linux.go
  network/transparent_vlan_endpointclient_linux.go
Labels: cni

#2574 ci: Add Cilium to CNI | LSG Integration Pipeline
  .pipelines/cni/lsg/kernel-upgrade-template.yaml
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/cni/lsg/pipeline.yaml
  test/internal/kubernetes/utils_create.go
Labels: ci
