Repository Azure/azure-container-networking, pull requests merged in 2025-09, with the labels that each got.

#3985 fix: add code generation to run-unit-tests.stages
  .pipelines/templates/run-unit-tests.stages.yaml
Labels: bug, cilium

#4010 Chore: make dependanbot to open one PR for go dependencies update weekly
  .github/dependabot.yaml
Labels: ci

#3914 ci: cns patch testing in release pipeline
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv2-template.yaml
  .pipelines/npm/npm-cni-integration-test.yaml
Labels: ci

#3930 feat: snat azure dns traffic to node ip in cns linux
  cns/restserver/internalapi_linux.go
  cns/restserver/internalapi_linux_test.go
Labels: cns, cilium
