Repository Azure/azure-container-networking, pull requests merged in 2025-06, with the labels that each got.

#3698 ci: output manifest tarball with Oras
  .pipelines/build/manifests.jobs.yaml
Labels: ci

#3648 feat: explicit optional compression in dropgz
  dropgz/README.md
  dropgz/cmd/payload.go
  dropgz/pkg/embed/payload.go
Labels: release/latest, dropgz, exempt-stale

#3248 fix: let Windows CNS use the InClusterConfig
  .pipelines/build/dockerfiles/cns.Dockerfile
  .pipelines/build/dockerfiles/cns.Dockerfile.tmpl
  cns/Dockerfile
  cns/Dockerfile.tmpl
  cns/azure-cns-windows.yaml
  test/integration/manifests/cns/daemonset-windows.yaml
Labels: cns, fix, exempt-stale

#3453 feat: add metric for NNC init failures
  cns/service/main.go
  cns/service/metrics.go
Labels: cns, release/latest, needs-backport, exempt-stale

#3745 [Service Tags] ci: Update ACN to use Virtual Tags
  hack/aks/Makefile
Labels: ci, needs-backport, release/1.5, release/1.6

#3739 ci: add azure ip masq merger to pipeline
  .pipelines/build/dockerfiles/azure-ip-masq-merger.Dockerfile
  .pipelines/build/ob-prepare.steps.yaml
  .pipelines/build/scripts/azure-ip-masq-merger.sh
  .pipelines/pipeline.yaml
  .pipelines/run-pipeline.yaml
  azure-ip-masq-merger/Dockerfile
  azure-ip-masq-merger/README.md
Labels: ci, cilium

#3750 [Service Tags] ci: Backport service/virtual tag updates to release/v1.5
  hack/aks/Makefile
Labels: ci, release/1.5

#3756 ci: add azure ipam and azure ip masq merger uts to pipeline
  .github/CODEOWNERS
  .pipelines/templates/run-unit-tests.yaml
  Makefile
Labels: ci, cilium
