Repository Azure/azure-container-networking, pull requests merged in 2025-02, with the labels that each got.

#3376 ci: increase goldpinger replicas from 4 to 8 and add topology constraints
  test/integration/manifests/datapath/linux-deployment-ipv6.yaml
  test/integration/manifests/datapath/linux-deployment.yaml
  test/integration/manifests/datapath/windows-deployment.yaml
Labels: ci, release/latest, needs-backport, release/1.5

#3380 backport: ci: increase goldpinger replicas from 4 to 8 and add topology constraints
  hack/aks/Makefile
  test/integration/manifests/datapath/linux-deployment-ipv6.yaml
  test/integration/manifests/datapath/linux-deployment.yaml
  test/integration/manifests/datapath/windows-deployment.yaml
Labels: ci, release/1.5

#3287 [NPM Lite] Support Network Policies Through CNS
  cni/network/invoker_cns.go
  cni/network/invoker_cns_test.go
  cni/network/network.go
  cni/network/network_windows_test.go
  network/endpoint.go
Labels: cni

#3381 feat: add levels to CNS AI logs
  aitelemetry/api.go
  aitelemetry/telemetrywrapper.go
  cns/logger/cnslogger.go
Labels: enhancement, cns, fix, release/latest

#3375 fix: route issues on Swiftv2 Windows
  cns/middlewares/k8sSwiftV2.go
  cns/middlewares/k8sSwiftV2_linux.go
  cns/middlewares/k8sSwiftV2_linux_test.go
  cns/middlewares/k8sSwiftV2_windows.go
  cns/middlewares/k8sSwiftV2_windows_test.go
Labels: cns

#3385 test: add ut to ensure store unaffected during add external interface
  network/manager_test.go
Labels: cni, release/1.4

#3415 [backport] ci: Unblock k8s 1.30 | ACN v1.6 testing (#3011)
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  hack/aks/Makefile
Labels: ci, release/1.5

#3414 Add dual stack fix's presence for AZR in CNS heartbeat metric
  cns/logger/constants.go
  cns/metric/heartbeat.go
Labels: AZR

#3405 chore: update windows base images for 1.5
  cni/windows.Dockerfile
  cns/windows.Dockerfile
  dropgz/build/linux.Dockerfile
  dropgz/build/windows.Dockerfile
Labels: release/1.5

#3400 fix: add iptables rules for dns in vnet scale cilium case
  cns/client/client_test.go
  cns/fakes/iptablesfake.go
  cns/restserver/api_test.go
  cns/restserver/internalapi_linux.go
  cns/restserver/internalapi_linux_test.go
  cns/restserver/internalapi_windows.go
  cns/restserver/ipam_test.go
  cns/restserver/restserver.go
  cns/restserver/v2/server_test.go
  cns/service/main.go
Labels: cns, fix, vnet-scale, release/1.5

#3426 ci: skip restart and validation test in dualstack windows
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-step-template.yaml
Labels: ci

#3421 forwardport: fix: add iptables rules for dns in vnet scale cilium case
  cns/client/client_test.go
  cns/fakes/iptablesfake.go
  cns/restserver/api_test.go
  cns/restserver/internalapi_linux.go
  cns/restserver/internalapi_linux_test.go
  cns/restserver/internalapi_windows.go
  cns/restserver/ipam_test.go
  cns/restserver/restserver.go
  cns/restserver/v2/server_test.go
  cns/service/main.go
Labels: cns, fix, release/latest, vnet-scale

#3432 ci: fix check-shadowing not allowed
  .golangci.yml
Labels: ci

#3382 feat: add apiserver FQDN to CNS log metadata
  cns/logger/cnslogger.go
  cns/logger/constants.go
  cns/logger/log.go
  cns/metric/heartbeat.go
  cns/service/main.go
Labels: enhancement, cns, fix, release/latest

#3431 ci: split dualstack and overlay e2e tests by operating system
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
  .pipelines/singletenancy/dualstack-overlay/dualstackoverlay-e2e-job-template.yaml
  Makefile
  hack/aks/Makefile
  hack/scripts/wait-cluster-update.sh
Labels: ci

#3433 fix: zapetw core With fields
  cni/log/logger_windows.go
  cns/logger/cnslogger_windows.go
  zapetw/core_windows.go
Labels: cns, cni, windows, release/latest

#3436 ci: unify windows and linux cluster creation methods
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/cni/pipeline.yaml
  .pipelines/cni/singletenancy/cniv1-template.yaml
  .pipelines/pipeline.yaml
  .pipelines/singletenancy/aks-swift/e2e-job-template.yaml
  .pipelines/singletenancy/aks/e2e-job-template.yaml
  .pipelines/templates/create-cluster.yaml
  hack/aks/Makefile
  hack/aks/README.md
Labels: ci

#3371 chore: use AppArmorProfile for cilium 1.16
  test/integration/manifests/cilium/daemonset.yaml
  test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset-dualstack.yaml
  test/integration/manifests/cilium/v1.16/cilium-agent/templates/daemonset.yaml
Labels: ci

#3379 ci: add k8s yaml deprecation check to nightly
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/templates/delete-cluster.yaml
  .pipelines/templates/k8s-yaml-test.yaml
Labels: cns, cni, ci

#3358 test: sort npm set policy values before validation
  npm/pkg/dataplane/ipsets/ipsetmanager_windows_test.go
Labels: npm

#3388 ci(cyclonus extended): [NPM] fix broken GH action
  .github/workflows/cyclonus-netpol-extended-nightly-test.yaml
Labels: npm, ci, linux

#3420 ci: [NPM] conformance test for loadbalancer and nodeport services
  .pipelines/npm/npm-conformance-tests.yaml
  npm/profiles/v2-background.yaml
  npm/profiles/v2-place-first.yaml
Labels: npm, ci, linux

#3439 fix: [NPM] [CVEs] Update NPM Linux Dockerfile to Fix Ubuntu Vulnerabilities
  npm/linux.Dockerfile
Labels: npm, linux

#3156 ci: combine go tests such that any test failure will report a failure for the entire task
  .pipelines/templates/run-unit-tests.yaml
  .pipelines/templates/unit-tests.stages.yaml
Labels: ci, release/latest, needs-backport, release/1.5

#3449 Expose GET NC list API in CNS client
  cns/NetworkContainerContract.go
  cns/api.go
  cns/restserver/api.go
  cns/restserver/api_test.go
  cns/restserver/restserver.go
  cns/types/codes.go
  nmagent/responses.go
Labels: AZR

#3455 backport: ci: fix check-shadowing not allowed (#3432)
  .golangci.yml
Labels: ci, release/1.4

#3456 backport: ci: fix check-shadowing not allowed (#3432)
  .golangci.yml
Labels: ci, release/1.5

#3372 tool: validator script for Azure NPM to Cilium migration
  tools/azure-npm-to-cilium-validator/README.md
  tools/azure-npm-to-cilium-validator/azure-npm-to-cilium-validator.go
  tools/azure-npm-to-cilium-validator/azure-npm-to-cilium-validator_test.go
  tools/azure-npm-to-cilium-validator/go.mod
  tools/azure-npm-to-cilium-validator/go.sum
Labels: npm, linux

#3437 feat: cns logger v2 [1/2]
  cns/logger/log.go
  cns/logger/v2/config.go
  cns/logger/v2/config_linux.go
  cns/logger/v2/config_test.go
  cns/logger/v2/config_windows.go
  cns/logger/v2/cores/ai.go
  cns/logger/v2/cores/ai_test.go
  cns/logger/v2/cores/etw_windows.go
  cns/logger/v2/cores/file.go
  cns/logger/v2/cores/file_test.go
  cns/logger/v2/cores/stdout.go
  cns/logger/v2/logger.go
  cns/logger/v2/logger_linux.go
  cns/logger/v2/logger_windows.go
  go.mod
  go.sum
  internal/time/duration.go
  internal/time/duration_test.go
Labels: cns

#3461 fix: [NPM] [CVEs] Update NPM Linux Dockerfile to Fix Ubuntu CVE-2024-12243
  npm/linux.Dockerfile
Labels: npm, linux
