Repository Azure/azure-container-networking, pull requests merged in 2025-04, with the labels that each got.

#3515 deps: go 1.23.0
  go.mod
Labels: dependencies, ci, release/1.4

#3553 chore: remove basic lb due to deprecation on 250930
  hack/aks/Makefile
Labels: ci, release/latest

#3543 ci: add fqdn with cilium local redirect policy test
  test/integration/lrp/lrp_fqdn_test.go
  test/integration/lrp/lrp_test.go
  test/integration/manifests/cilium/lrp/fqdn-cnp.yaml
  test/internal/datapath/datapath_win.go
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_create.go
  test/internal/kubernetes/utils_delete.go
  test/internal/kubernetes/utils_parse.go
  test/validate/linux_validate.go
  test/validate/validate.go
  test/validate/windows_validate.go
Labels: ci

#3554 chore: remove basic lb due to deprecation on 250930 (v1.4)
  hack/aks/Makefile
Labels: ci, release/1.4

#3544 ci: add code coverage publishing and check to pipeline
  .pipelines/templates/run-unit-tests.yaml
  Makefile
Labels: ci

#3555 chore: remove basic lb due to deprecation on 250930 (v1.5)
  hack/aks/Makefile
Labels: ci, release/1.5

#3457 ci: add vnet scale cilium pipeline stage
  .pipelines/pipeline.yaml
  hack/aks/Makefile
Labels: ci

#3277 ci: [Service Tags] add public ips with service tags for LBs during cluster creation
  hack/aks/Makefile
Labels: ci

#3575 ci: Allow manual overwrite of k8s version in CI/CD
  .pipelines/cni/load-test-templates/create-cluster-template.yaml
  .pipelines/templates/create-cluster.jobs.yaml
  .pipelines/templates/create-cluster.yaml
  hack/aks/Makefile
Labels: ci

#3584 ci: enable lrp in cilium 1.13 config
  test/integration/manifests/cilium/v1.13/cilium-config/cilium-config.yaml
Labels: ci

#3503 ci: Populate missing fields in CNS configmap
  test/integration/manifests/cnsconfig/azurecnidualstackoverlaylinuxconfigmap.yaml
  test/integration/manifests/cnsconfig/azurecnidualstackoverlaywindowsconfigmap.yaml
  test/integration/manifests/cnsconfig/azurecnioverlaylinuxconfigmap.yaml
  test/integration/manifests/cnsconfig/azurecnioverlaywindowsconfigmap.yaml
  test/integration/manifests/cnsconfig/azurestatelesscnioverlaywindowsconfigmap.yaml
  test/integration/manifests/cnsconfig/ciliumconfigmap.yaml
  test/integration/manifests/cnsconfig/ciliumnodesubnetconfigmap.yaml
  test/integration/manifests/cnsconfig/overlayconfigmap.yaml
  test/integration/manifests/cnsconfig/swiftlinuxconfigmap.yaml
  test/integration/manifests/cnsconfig/swiftwindowsconfigmap.yaml
Labels: ci

#3607 ci: set aks preview to 14.0.0b3
  hack/aks/Makefile
Labels: fix, ci
