Repository Azure/azure-container-networking, pull requests merged in 2025-05, with the labels that each got.

#3619 ci: required changes for LTS support | v1.5
  hack/aks/Makefile
Labels: ci, release/1.5

#3602 fix: validate iptable rule exists after calling insert or append iptable rule
  iptables/iptables.go
  iptables/iptables_test.go
Labels: cni, fix, linux, multitenancy

#3618 Revert "ci: set aks preview to 14.0.0b3"
  hack/aks/Makefile
Labels: ci

#3592 ci: Add check for cilium error logs to cilium nightly pipeline
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/templates/log-check-template.yaml
Labels: ci

#3563 backport: retry restarting HNS (#3529, #3540)
  platform/os_windows.go
  platform/os_windows_test.go
Labels: cns, fix, release/1.5

#3614 revert: [NPM] [v1.5] Remove hostUsers Configuration
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/npm/npm-scale-test.yaml
  npm/azure-npm.yaml
Labels: npm, linux

#3612 revert: [NPM] Remove hostUsers Configuration
  .pipelines/npm/npm-conformance-tests.yaml
  .pipelines/npm/npm-scale-test.yaml
  npm/azure-npm.yaml
  npm/examples/azure-npm-lite.yaml
Labels: npm, linux

#3620 ci: future proof for LTS clusters
  hack/aks/Makefile
Labels: ci, release/1.4, release/latest, needs-backport, release/1.5

#3627 [backport] ci: future proof for LTS clusters (#3620)
  hack/aks/Makefile
Labels: ci, release/1.4

#3639 ci: create test image vars for release test
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
Labels: ci

#3640 chore: update tolerations in cilium operator manifests, makefile fix
  hack/aks/Makefile
  test/integration/manifests/cilium/v1.13/cilium-operator/templates/deployment.yaml
  test/integration/manifests/cilium/v1.14/cilium-operator/templates/deployment.yaml
  test/integration/manifests/cilium/v1.16/cilium-operator/templates/deployment.yaml
Labels: ci

#3626 [forwardport] ci: future proof for LTS clusters (#3620)
  hack/aks/Makefile
Labels: ci

#3655 [ci] fix: make variable assignment
  hack/aks/Makefile
Labels: ci

#3647 ci: use publish code coverage results v1
  .pipelines/templates/run-unit-tests.yaml
Labels: ci

#3624 ci: mtu check for cilium e2e
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
  .pipelines/templates/cilium-mtu-check.yaml
  .pipelines/templates/cilium-tests.yaml
  hack/manifests/nginx.yaml
  hack/scripts/cilium-mtu-validation.sh
Labels: ci

#3680 revert: [NPM] [CVEs] Revert Manual NPM Linux Dockerfile Package Installations
  npm/linux.Dockerfile
Labels: npm, linux
