Repository Azure/azure-container-networking, pull requests merged in 2025-03, with the labels that each got.

#3488 backport: ci: combine go tests such that any test failure will report a failure for the entire task (#3156)
  .pipelines/templates/run-unit-tests.yaml
Labels: ci, release/1.5

#3476 [Swiftv2 L1VH]Add multiple IB NICs UT
  cni/network/invoker_cns_test.go
Labels: cni

#3468 fix: [NPM] Reduce/Refactor Noisy NPM Logs
  npm/azure-npm.yaml
  npm/cmd/start.go
  npm/cmd/start_daemon.go
  npm/cmd/start_server.go
  npm/config/config.go
  npm/metrics/ai-utils.go
  npm/pkg/controlplane/controllers/v2/namespaceController.go
  npm/pkg/controlplane/controllers/v2/networkPolicyController.go
  npm/pkg/controlplane/controllers/v2/podController.go
  npm/pkg/dataplane/dataplane.go
  npm/pkg/dataplane/dataplane_linux_test.go
  npm/pkg/dataplane/dataplane_test.go
  npm/pkg/dataplane/dataplane_windows_test.go
  npm/pkg/dataplane/ipsets/ipsetmanager.go
  npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
  npm/pkg/dataplane/types.go
  npm/util/const.go
  npm/util/ioutil/restore.go
Labels: npm, linux

#3494 [backport] [NPM] Reduce/Refactor Noisy NPM Logs
  npm/azure-npm.yaml
  npm/cmd/start.go
  npm/cmd/start_daemon.go
  npm/cmd/start_server.go
  npm/config/config.go
  npm/metrics/ai-utils.go
  npm/pkg/controlplane/controllers/v2/namespaceController.go
  npm/pkg/controlplane/controllers/v2/networkPolicyController.go
  npm/pkg/controlplane/controllers/v2/podController.go
  npm/pkg/dataplane/dataplane.go
  npm/pkg/dataplane/dataplane_linux_test.go
  npm/pkg/dataplane/dataplane_test.go
  npm/pkg/dataplane/dataplane_windows_test.go
  npm/pkg/dataplane/ipsets/ipsetmanager.go
  npm/pkg/dataplane/ipsets/ipsetmanager_linux.go
  npm/pkg/dataplane/types.go
  npm/util/const.go
  npm/util/ioutil/restore.go
Labels: npm, linux

#3498 fix: don't restart HNS if the ARP regkey is not changed
  cns/service/main.go
  platform/os_windows.go
Labels: cns, fix, windows

#3501 ci: remove beta kubernetes os selector
  .pipelines/mdnc/azure-cns-cni-1.4.39.1.yaml
  .pipelines/mdnc/azure-cns-cni-1.5.28.yaml
  .pipelines/mdnc/azure-cns-cni-1.5.4.yaml
  .pipelines/mdnc/azure-cns-cni.yaml
  cns/azure-cns.yaml
  hack/manifests/cni-installer.yaml
  hack/toolbox/manifests/agents.yaml
  hack/toolbox/manifests/daemonset.yaml
  hack/toolbox/manifests/master.yaml
  test/integration/manifests/cilium/cns-write-ovly.yaml
  test/integration/manifests/cns/daemonset-linux.yaml
  test/scale/templates/kwok-node.yaml
  tools/acncli/deployment/manager_swift.yaml
Labels: ci

#3502 fix: set EnableIPAMv2 to true for current release train
  test/integration/manifests/cnsconfig/azurecnidualstackoverlaylinuxconfigmap.yaml
  test/integration/manifests/cnsconfig/azurecnidualstackoverlaywindowsconfigmap.yaml
  test/integration/manifests/cnsconfig/azurecnioverlaylinuxconfigmap.yaml
  test/integration/manifests/cnsconfig/azurecnioverlaywindowsconfigmap.yaml
  test/integration/manifests/cnsconfig/azurestatelesscnioverlaywindowsconfigmap.yaml
  test/integration/manifests/cnsconfig/ciliumconfigmap.yaml
  test/integration/manifests/cnsconfig/ciliumnodesubnetconfigmap.yaml
  test/integration/manifests/cnsconfig/overlayconfigmap.yaml
  test/integration/manifests/cnsconfig/swiftwindowsconfigmap.yaml
Labels: cns, ci, release/latest

#3499 [PONv6] Add 3 new fields to NC.
  crd/nodenetworkconfig/api/v1alpha/nodenetworkconfig.go
  crd/nodenetworkconfig/manifests/acn.azure.com_nodenetworkconfigs.yaml
Labels: cns

#3516 ci: remove toolchain usage
  go.mod
Labels: ci, release/latest

#3514 deps: go 1.23.0
  go.mod
Labels: dependencies, ci, release/1.5

#3500 ci: add cilium local redirect policy test to nightly pipeline
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  go.mod
  go.sum
  test/integration/lrp/lrp_test.go
  test/integration/manifests/cilium/cilium-nightly-config.yaml
  test/integration/manifests/cilium/lrp/client-ds.yaml
  test/integration/manifests/cilium/lrp/config-map.yaml
  test/integration/manifests/cilium/lrp/lrp.yaml
  test/integration/manifests/cilium/lrp/node-local-dns-ds.yaml
  test/integration/manifests/cilium/lrp/service-account.yaml
  test/integration/manifests/cilium/lrp/service.yaml
  test/integration/manifests/cilium/v1.14/cilium-config/cilium-config.yaml
  test/integration/manifests/cilium/v1.16/cilium-config/cilium-config.yaml
  test/integration/manifests/cilium/v1.17/cilium-config/cilium-config.yaml
  test/integration/networkobservability/hubble_test.go
  test/integration/prometheus/prometheus.go
  test/integration/prometheus/prometheus_test.go
  test/internal/kubernetes/utils.go
  test/internal/kubernetes/utils_create.go
  test/internal/kubernetes/utils_delete.go
  test/internal/kubernetes/utils_get.go
  test/internal/kubernetes/utils_parse.go
Labels: ci

#3518 fix: [NPM] [CVEs] Update go.mod to Fix NPM golang.org/x/net CVE-2025-22870
  go.mod
  go.sum
Labels: npm, linux

#3519 fix: modify cleanup path to always delete link
  netlink/mocknetlink.go
  network/transparent_vlan_endpointclient_linux.go
  network/transparent_vlan_endpointclient_linux_test.go
Labels: cni, fix, multitenancy

#3525 ci: release test skip npm k8s e2e linux podsubnet
  .pipelines/npm/npm-cni-integration-test.yaml
Labels: ci

#3529 fix: carefully retry restarting HNS if it hangs
  platform/os_windows.go
  platform/os_windows_test.go
Labels: cns
