Repository Azure/azure-container-networking, pull requests merged in 2025-07, with the labels that each got.

#3766 [Forwardport] [NPM] [CVE] Resolve CVE-2025-6020
  npm/linux.Dockerfile
Labels: npm, linux

#3782 [NPM] fix: Update Iptables to Legacy
  npm/pkg/dataplane/policies/chain-management_linux_test.go
  npm/pkg/dataplane/policies/testutils_linux.go
  npm/util/const.go
Labels: npm, linux

#3792 [backport] #3791 ci: only check for code coverage at merge, not release
  .pipelines/templates/run-unit-tests.yaml
Labels: fix, ci, release/1.6

#3803 ci: enable merge queue for release/v1.6
  .pipelines/pipeline.yaml
Labels: ci

#3772 ci: cleanup Cilium cli and connectivity test usage
  .pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
  .pipelines/cni/cilium/nightly-release-test.yml
  .pipelines/cni/lsg/lsg-cni-intergration-template.yaml
  .pipelines/networkobservability/pipeline.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-dualstack-overlay/cilium-dualstackoverlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e.steps.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e-step-template.yaml
  .pipelines/singletenancy/cilium-overlay/cilium-overlay-e2e.steps.yaml
  .pipelines/templates/cilium-connectivity-tests.yaml
  .pipelines/templates/cilium-tests.yaml
Labels: ci, cilium

#3842 [Forwardport] [NPM] fix: Update Iptables to Legacy (#3782)
  npm/pkg/dataplane/policies/chain-management_linux_test.go
  npm/pkg/dataplane/policies/testutils_linux.go
  npm/util/const.go
Labels: npm, linux

#3729 feat: create new telemetry handle that supports connection strings
  aitelemetry/connection_string_parser.go
  aitelemetry/connection_string_parser_test.go
  aitelemetry/telemetrywrapper.go
  aitelemetry/telemetrywrapper_test.go
  go.mod
  go.sum
Labels: swift

#3859 ci: Fixing build pipeline for 1.6 release
  .pipelines/build/generate-manifest.steps.yaml
  .pipelines/build/image.steps.yaml
  .pipelines/build/images.jobs.yaml
Labels: fix, ci

#3860 ci: Unblocking ADO build pipeline
  .pipelines/build/generate-manifest.steps.yaml
  .pipelines/build/image.steps.yaml
  .pipelines/build/images.jobs.yaml
  .pipelines/build/ob-prepare.steps.yaml
  .pipelines/run-pipeline.yaml
Labels: fix, ci

#3779 feat: add azure iptables monitor binary and makefile changes
  Makefile
  azure-iptables-monitor/Dockerfile
  azure-iptables-monitor/README.md
  azure-iptables-monitor/go.mod
  azure-iptables-monitor/go.sum
  azure-iptables-monitor/iptables_monitor.go
  azure-iptables-monitor/iptables_monitor_test.go
Labels: linux, cilium

#3870 ci: remove windows2019 from release test pipeline
  .pipelines/cni/pipeline.yaml
Labels: ci
